### ISSUE TITLE
Fail to load config file

### ISSUE THREAD

**Issue by leedstime** [jwplayer/jw-showcase#100]
Hi,
Thank you for you help.

### Expected Behavior

Showcase working

### Actual Behavior

"Fail to load config file"

### Steps to reproduce

1.
2.
3.

### Environment
Just drag the last precompiled_static_app on the server and change the index file with the right folder adress. Player key and playlist id inserted in the config file.
- https://leedstime.com/jwp/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @leedstime,

Your config.json is invalid. There is a comma after `"playlists": "aOuTxI09",`. Also the playlists value should be an array like `"playlists": ["aOuTxI09"]`

Tip; you can use http://jsonlint.com to validate JSON files free online.
