### ISSUE TITLE
Full screen Ads delivery

### ISSUE THREAD

**Issue by musictelevision** [jwplayer/jw-showcase#103]
### Expected Behavior

When viewing a film in full screen mode, on a mobile device, we're expecting linear video commercials to play properly in full screen mode, with the film restarting after the end of the commercial or ad pod break.

### Actual Behavior

When we come to a commercial break, in full screen mode, the video pauses like it should. About 50% of the time, we're able to hear the audio of the commercial playing (the other 50% of the time, from a user perspective, it seems as if the screen / video / player has frozen). By clicking done, we're brought back to the video page, where the video commercial and or ad pods play perfectly, in a small screen view, the view with the film description below. 

### Steps to reproduce

1. Visit www.legendstv.com from a mobile device
2. click on any of the film arts
3. Skip past the first two commercial breaks (we're doing some integration work with a new Ad Exchange, so the third break and beyond are going to be far more useful). We'll be making updates to our CORS header and SSL, making it easier for more ads to display for us. Getting this taken care of at the same time is going to be VERY helpful for us!

### Environment

- Safari, iPhone 5
- iOS |10.2.1
- Current Showcase Version | www.legendstv.com

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @musictelevision,

Could you report this in the jwplayer repository? https://github.com/jwplayer/jwplayer/issues
