### ISSUE TITLE
Video Title Parameter 

### ISSUE THREAD

**Issue by musictelevision** [jwplayer/jw-showcase#104]
### Expected Behavior

Hi guys, we're in the middle of a mobile integration with our Ad Exchange SpotX. JW and SpotX work extremely well together. 

As you guys know, ad tag and player macros work together to pass a great deal of information for ad delivery to consumer devices. It looks like JW player is working with a deprecated macro "vid_t" , rather than the valid paramter "vid_title"

### Actual Behavior

vid_t is being passed, rather than "vid_title"

### Steps to reproduce

1. www.legendstv.com/mobile
2. We're using the same ad tags across films, as a master tag for the time being

### Environment

- * iPhone / Android*
- *iOS / Android* 
- *Current Version*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @musictelevision,

Could you report this in the jwplayer repository? https://github.com/jwplayer/jwplayer/issues
