### ISSUE TITLE
How to make videos searchable

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#106]
### Expected Behavior

Click the search button, type in something and it pops up a list of videos depending on what you typed. 

### Actual Behavior

Added a tag to my video, (Welcome to AAPEX TV 360!) as "cats" and when I search this it returns no results. 

### Steps to reproduce

1. go to http://cntvnow.com/aapex/gallery
2. search for "cats"
3. no results. 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
You are using the Showcase demo search playlist in your config.json, which does not index your videos. You need to create your own search playlist in your JW Dashboard (note that search & recommendations playlists require an Enterprise license).
