### ISSUE TITLE
Custom Ad Tag Variables Not Populating

### ISSUE THREAD

**Issue by jlieb10** [jwplayer/jw-showcase#114]
### Expected Behavior

An ad tag with variables such as "__category__" and "__series__" that have custom fields for these on the video will populate accordingly

### Actual Behavior

Custom fields do not populate.

### Steps to reproduce

1. Use this tag: https://pubads.g.doubleclick.net/gampad/ads?sz=640x360&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&vad_type=linear&vpos=preroll&correlator=__random-number__&iu=/4160/mv.fc/__item-category__/__item-series__/preroll_showcase&cust_params=video_tags%3D__item-tags__%26vport=l%26video_id=__item-mediaid__
2. Notice that __item-mediaid__ & __random-number__ populate correctly
3. Notice that __item-category__ & __item-series__ do not populate even though they do when we use a different player on other parts of our site
4. I am told this is a known issue 

### Environment

- *hardware | device* MacBook Pro (Retina, Mid 2012) 15" 
- *operating system | version* macOS Sierra 10.12.4 (16E195)
- *JW Showcase v3.1 | https://www.fastcompany.com/videos/*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
I see the problem, I've added this to the roadmap!

**Comment by johnluther** [comment]
@jlieb10 Can you test the 3.2 Beta release and verify that it fixes the issue for you?

https://github.com/jwplayer/jw-showcase/tree/v3.2.0-beta
