### ISSUE TITLE
Logo Header Scalability 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#115]
### Expected Behavior

The logo/ header area should be scalable to whatever size you want. i.e. the logo should be however large or small you want it. This should also not effect the playlists. They should not be cut off at the bottom when you scroll. 

### Actual Behavior

Currently the logo is set to 90px only. I would like to place any size logo in the header. When I scroll the content near the bottom of the page should not be cut off. 

### Steps to reproduce

1. Navigate to http://cntvnow.com/gallery
2. Scroll all the way to the bottom. No matter if the header is on or off it still does the same thing. 

### Environment

- iMac 
- OSx Sierra 
- JW Showcase 3.1 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
We will need to evaluate this and determine if allowing logos with unknown/arbitrary height will create unpredictable layout behavior.

If you have specific layout requirements, building from source with customized SASS might be your best option.

**Comment by ChristiaanScheermeijer** [comment]
You have opened three equal issues which all address this problem: #67, #95, #96 

If you want the header to be larger, you should indeed create a custom build. Another option is to disable the header by changing `enableHeader` in the config.json.
