### ISSUE TITLE
Closed Captioning Not Working 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#116]
### Expected Behavior

Closed captioning should work on the JW Showcase. When I go to a video that has an SRT file uploaded via my JW dashboard, it should have closed captions for that video. 

### Actual Behavior

When I upload the file it works on the preview page of my JW dashboard. When I go to the Showcase and press closed captions on that video, it does not work... 

### Steps to reproduce

1. Go to http://navc.com/spark/list/LKeuX5ys/video/XLrHdIaq/cadaver-replacement
2. Try to press closed captions, notice that it does not work.. 

![screen shot 2017-04-11 at 4 33 15 pm](https://cloud.githubusercontent.com/assets/20861873/24929629/9745c464-1ed4-11e7-824c-35187cee6be6.png)
![screen shot 2017-04-11 at 4 33 02 pm](https://cloud.githubusercontent.com/assets/20861873/24929628/97458cf6-1ed4-11e7-8eb6-6fd543b4671b.png)

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by akashpatel0427** [comment]
The 3.2 version is not an ideal version for me, I think it makes the banner image at the top even worse... This has already been an issue with me in the past and thought that would be a milestone of your guys. 

All in all how can I use 3.1 version to fix the closed caption? The 3.2 makes the bar at the top floating and cuts and scrolls over all my content.

**Comment by johnluther** [comment]
@akashpatel0427 You will need to clone the 3.1 source to your machine, then make the two small changes that are recorded in https://github.com/jwplayer/jw-showcase/pull/111/files, and then rebuild using ```grunt build``` and copy the contents of the dist/ folder to your web server.

**Comment by akashpatel0427** [comment]
Okay that seems beyond my level of configurations. I am not sure where to begin. Is there another alternative? 

Thanks for your help in advance.

**Comment by johnluther** [comment]
@akashpatel0427 The attached example uses 3.2 Beta and doesn't break your custom banner.

[dist.zip](https://github.com/jwplayer/jw-showcase/files/920572/dist.zip)

**Comment by akashpatel0427** [comment]
Thank you, is it configured to now have a menu bar? http://cntvnow.com/navc/

**Comment by johnluther** [comment]
Sorry, you're right, I must have had something cached.

**Comment by akashpatel0427** [comment]
ok thank you,

**Comment by akashpatel0427** [comment]
Hi I just wanted to check in and see if there was going to be a new build or should I just leave the bug there? 

Thank you for your help

**Comment by johnluther** [comment]
With 3.2 being so close we won't do a hotfix of 3.1. 

This is a 3.1 build with the VTT fixed for you: 
[dist.zip](https://github.com/jwplayer/jw-showcase/files/922613/dist.zip)

I would still recommend hiring a freelance developer to make the header customizations you want to 3.2 when it comes out, otherwise you will be missing out on some major speed improvements in 3.2.

**Comment by akashpatel0427** [comment]
Everything seems great, and yes I will look into that. Thank you for all your help.
