### ISSUE TITLE
Keyboard-Only Accessibility for JW Showcase 

### ISSUE THREAD

**Issue by geneLellis** [jwplayer/jw-showcase#117]
### Expected Behavior

The ability to navigate through JW Showcase by using the keyboard 

### Actual Behavior

The keyboard has no function, meaning JW Showcase cannot be used for Smart TV HTML5 apps

### Steps to reproduce (feature request)

We have an HTML5 video app running on Smart TVs and we would like to replace the HTML5 video player with a JW Player so that it can be monetized. JW Showcase is a great way to showcase our content, especially since it is in HTML. We were disappointed to find out that the keyboard cannot be used to navigate through JW Showcase. This is a requirement for all of our Smart TV implementations. Right now we're looking at building a version of JW Showcase by hand so that it complies with our non-keyboard requirement.  If there is an easier way than rebuilding from scratch, we would love to hear it. Thank you!

### Environment

- Dell Laptop
- Windows 10
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Hi, Gene. The best approach is probably to implement it by hand to suit your specific requirements. We don't officially support Showcase on SmartTVs so we can't be sure how it will behave in those environments.

However, we should look into adding basic keyboard navigation to Showcase in a future version.

**Comment by geneLellis** [comment]
Hello John,

Thank you for the email. Yes, that's what we're thinking as well. Thanks
again!

Gene

**Comment by johnluther** [comment]
Created #118 so we can track implementing it in a future release.

**Comment by geneLellis** [comment]
Excellent! Thanks!

**Comment by johnluther** [comment]
@geneLellis , we implemented basic keyboard controls today in the Develop branch if you want to test it on your platform. 

Note that you will need to pull from the Develop branch of jw-showcase-lib to get the changes. Run `bower install jwplayer/jw-showcase-lib#develop` after the `npm install` command when [building from the source code](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code).

**Comment by geneLellis** [comment]
Now that's great news! Thanks! Can't wait to check this out!

**Comment by geneLellis** [comment]
I followed all of the instructions exactly and put the resulting dist file
here:
http://labs.baeblemusic.com/

Can you please explain where to find the keyboard controls? At the moment,
it seems to operate the same as before. I appreciate your assistance. We're
eager to try this out. Thanks!

Gene

**Comment by geneLellis** [comment]
Just wanted to re-confirm the following steps:

git clone https://github.com/jwplayer/jw-showcase.git
gem install compass
npm i grunt-cli -g
npm i bower -g
cd /jw-showcase/app
npm install
bower install jwplayer/jw-showcase-lib#develop
run grunt build

Then copy the dist file to the website. That's what I did, but I don't see
any keyboard functionality. Am I missing a step? Thanks!

**Comment by johnluther** [comment]
Thanks, @geneLellis . I'm able to Tab through that site. Tab navigated through the page elements top to bottom. Shift+Tab goes bottom to top (i.e., "reverse").

Can you tell us more about your expectations?

**Comment by geneLellis** [comment]
Thanks a lot @johnluther. Really appreciate the response. I didn't notice the tabbing functionality. Very cool! Unfortunately for our Smart TV implementation, we are limited to the arrow keys to move through the page elements. Any idea how we could possibly tweak this to use the arrow keys instead? 

Thanks! Really exciting!

**Comment by johnluther** [comment]
@ChristiaanScheermeijer , any ideas?

@geneLellis do you happen to know the Javascript Char codes that those remotes send for right/left/up/down? You might be able to get them by visiting http://keycode.info/ on the device.

**Comment by geneLellis** [comment]
The remotes are using the same codes as coming from a traditional keyboard.
We are just restricted to the keys we can use. Commonly they are:

- Up Arrow
- Down Arrow
- Left Arrow
- Right Arrow
- Enter Key
- Backspace

So essentially, we're trying to be able to control all the elements using
only those key codes. The tabbing functionality is a huge step forward. If
we map that to the arrow keys, then we'll really be in business.

**Comment by ChristiaanScheermeijer** [comment]
I really hoped for that by adding tabindex's Smart TV's (apps) would automatically recognise these and translate the up/down/left/right buttons to navigate through these elements. Maybe there are libraries available for your Smart TV App?

Left and right would be relatively easy to implement as its the same behaviour as pressing tab and shift+tab e.g. navigating to the next or previous element. Supporting up and down is a different case as we need to map each position of all focusable elements in the viewport and find the closest focusable element in a vertical line.

I think this is really specific to Smart TV Apps because opening JW Showcase in a browser on a Smart TV it works because there is a cursor which you can move with the D-Pad or arrow keys.

**Comment by geneLellis** [comment]
Hey Christiaan,

It's possible that Smart TVs will recognize the tab index when running from
within a browser. The app that we have developed for Smart TVs is fully
HTML, but does not run within a browser. However now that the tabbing
elements have been added into JW Showcase, it makes it a lot more feasible
to update our app by switching over to JW Showcase. As you said, the left
and right arrow for tabbing is straight forward. The up and down would need
a bit more work. One of the the constraints we were given by the Smart TV
companies is to have the app completely navigable without relying on a
cursor since it doesn't run in a standalone browser, even though it is HTML.

I'm thinking that I could accomplish all of this needed functionality by
writing some custom jqeury and weaving it into the code. Can you think of
any limitations using this method? Any other suggestions?

**Comment by ChristiaanScheermeijer** [comment]
I think that should work just fine :+1: 

I briefly experimented with https://github.com/nekman/keynavigator but I couldn't get it to work in Showcase out of the box. It can still be interesting for your application though.

A good thing to know: JW Showcase is a single page application. Meaning your custom code needs to hook into events and search all focusable elements when the page updates. One of these events would probably be `$stateChangeSuccess`.

**Comment by geneLellis** [comment]
Great! Thanks a lot for the message! I will dive on in and keep you posted!
If you have any other updates to the fork, please let me know

**Comment by geneLellis** [comment]
Quick question guys. We're editing JW Showcase to use our own CDN instead
of hosting the content in playlists on JW Player's platform.
When we did this with version 2.0.0, we edited the following file:
app/scripts/services/api.service.js and well as the app/config.json file.

Now that we are experimenting with the latest dev version, can you point me
in the right direction for which files I need to edit to do the same? It
looks like the file structure has changed. Thank you!

**Comment by ChristiaanScheermeijer** [comment]
Sure thing! If you just want to use your cdn you can add the `contentService` property to your config.json.

**Comment by ChristiaanScheermeijer** [comment]
You can also use the 3.4.0 version as this has been released yesterday!

**Comment by geneLellis** [comment]
Thanks for the email Christiaan,

Can you please explain a bit more regarding the contentService property?

We have 6 feeds. Each has it's own unique URL. I'm not quite too clear on
what needs to be placed in the config.json file. Here is one of our feeds. For
simplicity sake, I have it only returning one item. This would be in a
"Concerts" section in JW Showcase
*http://svc.baeblemusic.com/BaebleService.svc/json/getAppleTvVideoData/con/1/1
<http://svc.baeblemusic.com/BaebleService.svc/json/getAppleTvVideoData/con/1/1>*

The corrending detail page for the one video in this list corresponds to:
http://svc.baeblemusic.com/BaebleService.svc/json/getConcertsJSONByID/802/mobile

You can see this referenced by the "802" media ID

Few of questions:

- How would I edit the config.json file to show this information?
- Can a description be added or just a title?
- Does JW Showcase support ads? If so, how can I pass it my ads url?
- Do I need to do anything additional for the video detail page in JW
Showcase

Thanks so much for your help. It's been many many months since the last
time we edited JW Showcase to use our own feeds and I know a lot has
changed since then. Just re-gaining our footing.

Thanks!

**Comment by geneLellis** [comment]
Hey Christiaan,

I realize I caught you on a weekend and my last email was quite detailed.
So fully understand that you may not have had a moment to check it out. But
any guidance on this would be a big help when you get a moment. We'll
really eager to get this out and just a few things are holding us back.
Thanks!

**Comment by ChristiaanScheermeijer** [comment]
Hi @geneLellis,

From release v3.0.0 we have separated the library and web codebase to two repositories. To setup a local development environment please read this [page](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code).

The `api.service.js` can be found in `bower_components/jw-showcase-lib/js/core/services/api.service.js`.

**- How would I edit the config.json file to show this information?**

After your explanation It became clear that this is not going to work in your case. The contentService option can only be used if you have a CNAME the JW Platform.

**- Can a description be added or just a title?**

Do you mean a shelve/playlist description? We don't support this yet, but it might be a nice feature request.

**- Does JW Showcase support ads? If so, how can I pass it my ads url?**

Not yet, but this is on the roadmap for the next release!

**- Do I need to do anything additional for the video detail page in JW
Showcase**

That is up to you! What do you want to change?

**Comment by geneLellis** [comment]
Hey Christiaan,

Thanks a lot for email. I may not have explained clearly. 

In version 2.0 of JW Showcase, we were given guidance from JW Player on how and where to edit the source code to allow JW Showcase to use our own CDN-hosted content. Our content is in feed format and worked just fine with version 2.0. With version 3.0, it seems that the code base has changed in such a way that we can no longer follow the same procedure.  If you can give us a bit of guidance on what changes should be made (and where to make them) to use our own hosted playlists, that we can swap out the JW Playlists for our own hosted playlists and will be in business. Thanks for your assistance!

**Comment by geneLellis** [comment]
Hey Christiaan,

I've been doing some digging and I think I'm getting closer. Specifically these two files:
- jw-showcase-master\test\features\support\mock.js
Line: 31
- jw-showcase-master\app\config.json
Line 24

Seems like if I make edits here, I can use my own CDN playlist feeds. Am I on the right track?

**Comment by ChristiaanScheermeijer** [comment]
The mock.js file is only being used for Feature testing, so this file should not be changed.

The files you need to edit are:

**Change URL endpoint**
https://github.com/jwplayer/jw-showcase-lib/blob/master/js/core/services/api.service.js#L47

**Change the response expectation (feeds are Objects which contain a playlist Array)** 
https://github.com/jwplayer/jw-showcase-lib/blob/master/js/core/services/api.service.js#L170

It looks like the example feed is not the same format as JW Platform. So I'm afraid that by only changing the api.service.js Showcase is not going to work as expected.

**Comment by geneLellis** [comment]
Hey Christiaan,

Thanks for the email and thanks for heads up on the api.service.js file. I will look in there,

I didn't quite understand what you meant by the last statement you mentioned: "It looks like the example feed is not the same format as JW Platform. So I'm afraid that by only changing the api.service.js Showcase is not going to work as expected."

So if I just change the api.service.js file, that won't be enough to simply use our CDN?

**Comment by geneLellis** [comment]
One more thing. Stepping back for a moment, if you could tell me high level view, what needs to happen to change JW Showcase to use our feeds and CDN. We did this once before with version 2.0 and it only took a small edit to two files. What needs to be done so we can do this with the latest version? It says "You can use JW Showcase with other content delivery platforms (or your own CDN), but you will need to modify the source code" on the GitHub description but I'm unclear on how and where to make these changes. The files and directory structure have changed since we last did this so any assistance you can provide would be great. What did you mean by "I'm afraid that by only changing the api.service.js Showcase is not going to work as expected." Will our feeds work? He's the example feed we'll be using for Featured:
http://svctest.baeblemusic.com/BaebleService.svc/json/getAppleTvVideoData/feat/1/50
Thanks for your help. Really spinning our wheels at the moment.

**Comment by geneLellis** [comment]
Hey Christiaan,

I think what you are saying is that our feed that we are using will not work with JW Showcase because of the formatting. I will look at one of the JW Showcase feeds and try to replicate that. Thank you.

**Comment by ChristiaanScheermeijer** [comment]
Hi @geneLellis,

That is correct. Of course, it is possible, but it would require a lot of changes. This prevents you from easily updating in the future. 

Here you can find the API Documentation: https://developer.jwplayer.com/jw-platform/docs/delivery-api-reference/#!/playlists/get_v2_playlists_playlist_id

**Comment by geneLellis** [comment]
Thanks for the link Christiaan. We'll give into this and create a new feed based on the URL you provided.

**Comment by geneLellis** [comment]
Hey Christiaan.

Question. What is the "link" node? I see it inside of the sample feed (https://content.jwplatform.com/v2/playlists/WXu7kuaW), but it is not explained in the documentation. Thanks!

![link](https://user-images.githubusercontent.com/1022570/27909929-23771744-627d-11e7-9e74-136ef49dc7c3.PNG)

**Comment by johnluther** [comment]
Hi, Gene. Those are there for legacy purposes. We use them to populate the `<link>` elements in our MRSS feeds. Some customers require them to be in the JSON feeds as well.

**Comment by geneLellis** [comment]
Hey John,

Thanks for the response. Should we just leave the value blank or fill it with a placeholder of some sort?

**Comment by johnluther** [comment]
Showcase doesn't use it, you can leave it blank.

**Comment by geneLellis** [comment]
Got it. Thanks!

**Comment by geneLellis** [comment]
Hey everyone,

I hope you had a good weekend. We believe we have the feed re-formatted in the correct way. Can you please take a quick look and let me know how this looks? 

http://svctest.baeblemusic.com/BaebleService.svc/json/getJWVideoListingJSON/5/feat

Thanks!

**Comment by johnluther** [comment]
Hi, Gene. Some notes:

- don't enclose duration, pubdate, width, height in quotes
- in some cases in yours, "label" is misspelled "labl"
- "images" should be "image"

Is there a reason why you are pointing all the MP4 file nodes to the same 1080p URLs? This won't cause problems in Showcase but it will create a poor UX for users who think they are selecting a low-bandwidth rendition but then get a high bandwidth stream.

JL

**Comment by geneLellis** [comment]
Hi John,

Thanks for the notes. I will make those changes.

Question. If we have the manifest file, what is the function of listing out all of the streams? Wouldn't this be handled by the manifest file? That's how we do it for JW Player on the web. 

My understanding is that there is only 1 mp4 that just scales/adjusts per screen size, but I will double check this information.

**Comment by geneLellis** [comment]
Hello. I just received confirmation. We only have 1 mp4, and then the HLS scales in size and speed. 

So, for our feed, if we only put the HLS source and the MP4 source, will all of the other sizing options still show up? OR does that somehow need to be notated in the feed as well? 

Thanks!

**Comment by johnluther** [comment]
The player will enumerate the available resolutions based on the HLS manifest..

**Comment by geneLellis** [comment]
oh got it. So we will delete everything but the HLS manifest since all available resolutions will be enumerated from there. If that's the case, does it matter what width and height are specified in the feed? Seems all of that information will be obtained from from the manifest. I saw JW Player was using 1280 x 720, so that's the value we used. Not sure if that matters. 
The JW Feed: http://bit.ly/2sEAcvK 

Thanks!

**Comment by johnluther** [comment]
I don't think Showcase uses the width & height from the playlist. @ChristiaanScheermeijer can you verify?

**Comment by ChristiaanScheermeijer** [comment]
I'm not sure. The width and height parameters for the HLS manifest are added recently in the Platform API. Showcase doesn't use these parameters, but the maybe the player does or eventually will do.

I wouldn't remove the mp4 just yet, as this is used as a fallback when HLS playback isn't supported by the platform or browser. 

When the MP4 file is being played, the qualities are not retrieved from the manifest, but from the list of MP4 sources in your playlist. If you have only one quality MP4, you won't have a quality selection in the player.

**Comment by johnluther** [comment]
> I wouldn't remove the mp4 just yet, as this is used as a fallback when HLS playback isn't supported by the platform or browser.

That is a very good point, I forgot about that, thanks!

**Comment by geneLellis** [comment]
Great! Thanks guys!

**Comment by geneLellis** [comment]
Hey guys. We finished implementing all of the feedback that you sent over regarding formatting our feeds. Here is one of them. If you can confirm that the formatting for this feed is correct, then we'll ensure the other feeds are completed in the same manner. Thanks!

http://svctest.baeblemusic.com/BaebleService.svc/json/getJWVideoListingJSON/5/feat

**Comment by geneLellis** [comment]
Hey guys. Just checking in. If you have a moment to verify the format of this feed, it will be a big help. We'll then base our other feeds on this one. 

Thanks!

**Comment by johnluther** [comment]
Hi, Gene. The MP4 width and height value still have quotes, otherwise it looks good to me.

**Comment by geneLellis** [comment]
Thank you for the heads up. I will make that change.

**Comment by geneLellis** [comment]
Hey guys,

Thanks for your help. Really appreciate it. We're finally up and running. Question for @ChristiaanScheermeijer. You mentioned that the next release of JW Showcase will include support for advertising. When do you expect that to be released? Thanks!

**Comment by johnluther** [comment]
Good to hear, @geneLellis . 

@hblee is the better person to answer the advertising question (he is on vacation this week, FYI).

**Comment by geneLellis** [comment]
Thanks @johnluther! Appreciate it!

@hblee, have a great vacation and I look forward to speaking with you next week!

**Comment by geneLellis** [comment]
Hello @hblee, one of my team brought this site to my attention saying they are running JW Showcase and have advertising playing: http://video.salon.com/
 I'm glad to see this functionality is out in the field. How do we get advertising in our player?
http://www.baeblemusic.com/tv

**Comment by hblee** [comment]
Hi @geneLellis, 

Are you referring to video ads or display ads? I'm not seeing display ads on video.salon.com but they are running video ads.

Video ads has been supported in Showcase very early on, but we actually just released Display Ad support in [Showcase version 3.5](https://github.com/jwplayer/jw-showcase/releases/tag/v3.5.0).

Here's some [support docs](https://github.com/jwplayer/jw-showcase/wiki/Adding-Display-Ads-To-Your-Showcase) and let me know if you have any questions.

Cheers
Henry

**Comment by geneLellis** [comment]
Hello all,
I came across this page when trying to get the 'search engine friendly' urls to function properly:
https://github.com/jwplayer/jw-showcase/wiki/Deploying-JW-Showcase

It gives instructions for Apache, Nginx, and Amazon S3. Any idea of the configurations for IIS?

**Comment by johnluther** [comment]
@geneLellis I haven't worked much with IIS but this seems to be the answer: https://stackoverflow.com/questions/12614072/how-do-i-configure-iis-for-url-rewriting-an-angularjs-application-in-html5-mode

I think your REQUEST_URI pattern will need to be:

```<add input="{REQUEST_URI}" pattern="^/(tv)" negate="true" />```

JL

**Comment by geneLellis** [comment]
Thanks @johnluther. I will dig deeper!

**Comment by geneLellis** [comment]
Hey @hblee,

When you get a moment, can you please let me know how we can enable ads inside of JW Showcase? We would love to run video ads just like http://video.salon.com/ but I don't see this anywhere in the documentation. Do we need to be a beta tester? Thanks!

**Comment by ChristiaanScheermeijer** [comment]
Hi @geneLellis,

You can enable video advertising via the [jwplayer dashboard](https://dashboard.jwplayer.com). Go the players page and select the player used in your config.json. On the left side, you will see an "Advertising" block. These settings will then be used by Showcase automatically.

**Comment by hblee** [comment]
Hi @geneLellis, sorry for the delay. Finishing up on my backlog from vacation. @ChristiaanScheermeijer is correct, the player configured for Showcase will need to have an ad schedule associated to run video ads.

**Comment by geneLellis** [comment]
Thanks a lot @hblee. I have configured advertising for www.baeblemusic.tv. If you could kindly let me know if you are seeing advertising on your end, I would really appreciate it. 

Also, I figured out the server configurations for IIS. Thanks! 

Question, is there a plan for JW Showcase to support Open Graph tags? I saw this because when you try to share a video in Facebook, the default is a preview picture from JW Showcase (attached). 
![share](https://user-images.githubusercontent.com/1022570/29661971-e784ba40-88ef-11e7-8752-500aed669fc0.PNG)

I thought may it was something I did wrong, but the behavior is the exact same for http://tv.jwplayer.com. I see that Salon made static Open Graph behavior (attached).  Was just wondering if something dynamic was coming down the pipe. Thanks!
![salon](https://user-images.githubusercontent.com/1022570/29662120-5c656940-88f0-11e7-8714-86ecee8b9bab.PNG)

**Comment by geneLellis** [comment]
Hey guys. Seem to be having trouble with ads. They are simply not showing up. Below are the screen shots for my setup. In terms of the advertising tag, I know it's correct because it's the same one that we are using for video ads on our production site. 

For example: http://www.baeblemusic.com/concert-video/baeble-hq/streets-of-laredo.html

what steps do you recommend for trouble shooting? Seems it should all just work. Any ideas?

Also, if there is a better place I should be placing tech support questions, please let me know. Thanks!
![1](https://user-images.githubusercontent.com/1022570/29699357-4d4ea2fa-8986-11e7-8e7a-97ab2c05c450.PNG)
![2](https://user-images.githubusercontent.com/1022570/29699358-4d4ea070-8986-11e7-9523-24bce1c20e31.PNG)
![3](https://user-images.githubusercontent.com/1022570/29699359-4d4f1f96-8986-11e7-81c2-4f7e0c68b004.PNG)

**Comment by ChristiaanScheermeijer** [comment]
Hi @geneLellis,

I don't see any advertising configuration in the player used in your Showcase. Have you made these modifications to the player with id "EjE3hSsH"?

**Comment by geneLellis** [comment]
Ahhh..wrong player. It's "lu4S73ar"

Just changed it and saw an ad. Thanks!

**Comment by ChristiaanScheermeijer** [comment]
Glad it works now! I will close this issue as it contains multiple topics.
