### ISSUE TITLE
Configuration setting for featured poster preview

### ISSUE THREAD

**Issue by monibons** [jwplayer/jw-showcase#119]
### Expected Behavior

I would like a configuration option to turn off the featured poster preview. Currently the thumbnails are not high res enough so it disrupts the experience rather than enhance.

Something like the below would be good:
"featuredCardPreview": false

### Actual Behavior

Currently no way to turn off this feature without editing source files of jw-showcase-lib.

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by monibons** [comment]
@josiekeller FYI

**Comment by ChristiaanScheermeijer** [comment]
Hi @monibons, @josiekeller I think by adding `enableFeaturedPreview` and `enableContinueWatchingPreview` will do the trick, do you agree?

@johnluther Does this fit in the new config model, or should this be a self hosted option only?

**Comment by johnluther** [comment]
Thanks, @ChristiaanScheermeijer , let's make it available in the new model, @hblee as FYI

**Comment by monibons** [comment]
@ChristiaanScheermeijer that works for me.

**Comment by ChristiaanScheermeijer** [comment]
Ok, after discussing with @nvang we thought it would be best to add this option to the `content` collection instead as a global setting.

`enableFeaturedText` is also going to be moved to the content items.

What do you think @johnluther?

```
{
  "version": "2",
  ...
  "content": [{
    "playlistId": "xyz123",
    "featured": true,
    "enablePreview": false,
    "enableText": false
  }]
}
```

**Comment by johnluther** [comment]
@ChristiaanScheermeijer that sounds good to me.

**Comment by ChristiaanScheermeijer** [comment]
This feature has been added in v3.3.0-beta!
