### ISSUE TITLE
Recommendation Overlay

### ISSUE THREAD

**Issue by angusykl** [jwplayer/jw-showcase#121]
### Expected Behavior

Once the video is done, it should come up the recommendation overlay. Also, the right top corner would have the button to show the recommendation overlay. 

### Actual Behavior

*No recommendation overlay come out after the video is finished
*No button on the top right corner

On the console, there is an error message stating that " Failed to load resource: the server responded with a status of 404 ()" for "content.jwplatform.com/v2/playlists/Trape1MS?related_media_id=NesQ0bWC". 

THE URL shows - {"message":"DYNAMIC playlists do not accept a related video"}

which I believe it's related to our recommendation playlist? 

### Steps to reproduce

1. Go into the Play Page ( list/*PlaylistID*/video/*MediaID*/05042017 )
2.Console log will show 404 error 
3.

### Environment

- PC Desktop
- Chrome 
- JW Showcase version 3.20

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Correct, you need to specify a JW Recommendations playlist ID in your config.json, the one you have is a Dynamic curated playlist.

Also, we don't support the player overlay yet in Showcase. Instead, we create a second content shelf below the video player called "Related Videos."

**Comment by johnluther** [comment]
Yes, we plan to support it in the future but don't have an exact timeline yet.

What is your site address?
