### ISSUE TITLE
Suspected Player Error

### ISSUE THREAD

**Issue by musictelevision** [jwplayer/jw-showcase#122]
### Expected Behavior
Video Playback works on most devices, so we expected that is works across mobile devices and mobile browsers. Works well on my iPhone, and we're seeing a pausing on another device

### Actual Behavior 
On a Samsung Note  5, using Chrome, when a user presses play, JW begins to play, shows the pre roll message "Ad will end in 15 seconds", then pauses. When the user presses play, it pauses again. 

### Steps to reproduce

1. visit www.legendstv.com from a Samsung Note 5, using Chrome 
2. Select any film art
3. Press Play

### Environment

- Samsung Note 5
- Android
- up to date 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by musictelevision** [comment]
+ @SongDog33

**Comment by ChristiaanScheermeijer** [comment]
@musictelevision have you already contacted support@jwplayer.com? This seems to be player related.
