### ISSUE TITLE
Update dependency package manager

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jw-showcase#125]
Bower recommends using yarn/NPM for dependencies:

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

https://github.com/bower/bower/issues/2298

**Comment by pajter** [comment]
Fixed with #171 and is now in release [v3.8.0](https://github.com/jwplayer/jw-showcase/releases/tag/v3.8.0).
