### ISSUE TITLE
Missing thumbnails on certain platforms when uploading

### ISSUE THREAD

**Issue by DiscoveryChristian** [jwplayer/jw-showcase#126]
### Thumbnails on video-contet
*When uploading video-content to our platforms (in example "Dplay.me") we expect to see the given thumbnail that we chose in JWplayer.*

### Missing thumbnails on certain platforms when uploading

*Some thumbnails are missing when they reach the platform (above example)

(url![discovery_showcase_page](https://cloud.githubusercontent.com/assets/29063214/26584315/abb4d99a-4548-11e7-8f97-e3cd86d26f67.png)
![discovery_showcase_dom](https://cloud.githubusercontent.com/assets/29063214/26584316/aed7bb74-4548-11e7-90c7-599f43ffce7a.png)

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @DiscoveryChristian, unfortunately I can't visit your Showcase due to geo restrictions.

**Comment by DiscoveryChristian** [comment]
Hi Christiaan.

That is right. You will to VPN into Denmark. Do you need more details of that?

________________________________
Fra: Christiaan Scheermeijer <notifications@github.com>
Sendt: 30. maj 2017 13:42:40
Til: jwplayer/jw-showcase
Cc: Christian Jensen; Mention
Emne: Re: [jwplayer/jw-showcase] Missing thumbnails on certain platforms when uploading (#126)


Hi @DiscoveryChristian<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdiscoverychristian&data=01%7C01%7Cchristian_jensen2%40discovery.com%7C22c8f4b2d17a472616c308d4a761c2f0%7C092a1ba4a4fe4172970e7ab3035e7c94%7C0&sdata=y2Nkx1IULMwj1CrwKgjqkHUI02O9YfF9DurUcBBU64I%3D&reserved=0>, unfortunately I can't visit your Showcase due to geo restrictions.

**Comment by ChristiaanScheermeijer** [comment]
Ah, I was unable to determine which country was whitelisted. I'll be fine thanks.

**Comment by ChristiaanScheermeijer** [comment]
I see there are multiple items that don't have defined an image. I'm not sure what the reason is but could you check JW Dashboard to see if video ''O1UvoHEA" (Engelsk fodbold-ekspert: »Dolberg er på hylden under Griezmann«) has an image?

**Comment by DiscoveryChristian** [comment]
Hi Christiaan.


I can see that it failed uploading the thumbnail, but that is pretty much the reason, that we are asking for your help. Do you know why this is happening?

________________________________
Fra: Christiaan Scheermeijer <notifications@github.com>
Sendt: 30. maj 2017 14:01:09
Til: jwplayer/jw-showcase
Cc: Christian Jensen; Mention
Emne: Re: [jwplayer/jw-showcase] Missing thumbnails on certain platforms when uploading (#126)


I see there are multiple items that don't have defined an image. I'm not sure what the reason is but could you check JW Dashboard to see if video ''O1UvoHEA" (Engelsk fodbold-ekspert: »Dolberg er på hylden under Griezmann«) has an image?

**Comment by johnluther** [comment]
@DiscoveryChristian This appears to be a JW Platform error unrelated to Showcase. Can you please contact support@jwplayer.com?

**Comment by DiscoveryChristian** [comment]
I have already been in touch with the Jwplayer-support, and they informed me to contact you regarding to this problem.

________________________________
Fra: John Luther <notifications@github.com>
Sendt: 30. maj 2017 15:21:44
Til: jwplayer/jw-showcase
Cc: Christian Jensen; Mention
Emne: Re: [jwplayer/jw-showcase] Missing thumbnails on certain platforms when uploading (#126)


@DiscoveryChristian<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdiscoverychristian&data=01%7C01%7Cchristian_jensen2%40discovery.com%7Ca8f37e98d4304cc0654608d4a76f9dfe%7C092a1ba4a4fe4172970e7ab3035e7c94%7C0&sdata=hasIbKxYHC0OTgNd5uXoynd4A2IEvzMKGldcg21wnWs%3D&reserved=0> This appears to be a JW Platform error unrelated to Showcase. Can you please contact support@jwplayer.com<mailto:support@jwplayer.com>?

**Comment by waxidiotic** [comment]
@DiscoveryChristian I am the Support Engineer who was originally helping you. Since @johnluther identified this as most likely being a platform issue, I'll re-open your support case and look deeper into this. As soon as I have something, I'll reply to that previous support case.

Thanks!

**Comment by johnluther** [comment]
OK, I will talk to support and try to get more info. It still seems to me that it's a Platform upload error. The "image" properties in the playlist for those items is null. If that field is null, Showcase can't populate the background image property in the CSS

**Comment by DiscoveryChristian** [comment]
Great, thanks.

I'm looking forward to hear from you.

________________________________
Fra: John Luther <notifications@github.com>
Sendt: 1. juni 2017 16:09:34
Til: jwplayer/jw-showcase
Cc: Christian Jensen; Mention
Emne: Re: [jwplayer/jw-showcase] Missing thumbnails on certain platforms when uploading (#126)


OK, I will talk to support and try to get more info. It still seems to me that it's a Platform upload error. The "image" properties in the playlist for those items is null. If that field is null, Showcase can't populate the background image property in the CSS
