### ISSUE TITLE
Colors & Sidebar....

### ISSUE THREAD

**Issue by BlackEnterprise** [jwplayer/jw-showcase#128]
### Expected Behavior

The color pink is used throughout, loading circle, arrows, titles and more. We want to be able to change the color.

The scrollbar you can barely see in the ride side of the browser is a very dark gray. We want to change the color.

### Actual Behavior

n/a

### Steps to reproduce

visit the site

### Environment

- desktop; chrome and firefox
- n/a
- latest

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by hblee** [comment]
Hi @BlackEnterprise, thanks for submitting your issue.  

You can change _highlightColor_ and _backgroundColor_ in the _config.json_ file.

To change the pink color, specify a color (in hexidecimal format) in the _highlightColor_ of _config.json_. For example, if you want yellow, set it to `"highlightColor": "#ff0"`. More info in our [Getting Started](https://github.com/jwplayer/jw-showcase/wiki/Getting-Started) doc.

To change the scrollbar color or other specific CSS styles, however, you will have to [build from source](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code).  You can also check out our wiki doc on [Customizing Showcase](https://github.com/jwplayer/jw-showcase/wiki/Customizing-JW-Showcase) for some more info.

We are continuously improving our documentation so we will endeavor to make this clearer.

Thanks!
Henry

**Comment by ChristiaanScheermeijer** [comment]
Unfortunately the highlightColor option isn't supported in Showcase 3.3. This will be added in the next release. You can however change the primary color when building from source. If you need help with that please let us know!

**Comment by BlackEnterprise** [comment]
Thanks!  When is your next release?

**Comment by ChristiaanScheermeijer** [comment]
Probably June 20. However, the beta release is planned for next week if you want to test this feature!

**Comment by ChristiaanScheermeijer** [comment]
Hi @BlackEnterprise, the beta release is ready and contains support for the highlightColor option!

**Comment by johnluther** [comment]
We officially released 3.4 today, closing this issue.
