### ISSUE TITLE
Changed Player Ids and Config file won't load now

### ISSUE THREAD

**Issue by PKSEvite** [jwplayer/jw-showcase#131]
### Expected Behavior

Config file load, Showcase page to load properly

### Actual Behavior

Error message "Failed to load config file" 

### Steps to reproduce

1. Changed Player IDs within config file
2. Uploaded our logo file named "logo.png"
3.

### Environment

- *iMac (Retina 5K, 27-inch, Late 2014)4 GHz Intel Core i7*
- *OS Sierra | 10.12.5*
- *JW Showcase version v3.3.0 | https://partners.evitecdn.com/jw/index.html*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @PKSEvite, thank you for using JW Showcase! It appears the config is trying to be resolved at a wrong location `https://partners.evitecdn.com/jw/jw/config.json`.

If you want Showcase to be hosted in the first `jw` subdirectory, change the `configLocation` value in index.html to `./config.json`.

**Comment by ChristiaanScheermeijer** [comment]
I'm closing this issue for now. Let me know if you still having issues!
