### ISSUE TITLE
Salon.com Showcase Failing to Load 

### ISSUE THREAD

**Issue by justinwohl** [jwplayer/jw-showcase#139]
I created a JW Showcase page but there's an error loading it. 

![image](https://user-images.githubusercontent.com/25830202/27390878-6b256e56-5670-11e7-89de-93528f9db460.png)

Can you check out my build please?
https://salon.jwpapp.com/

**Comment by johnluther** [comment]
Hi, Justin.  The version of Showcase in the JW Dashboard is running an older build that doesn't support Trending playlists. We are in the process of updating to a version that supports them in the next couple weeks.

In the meantime, can you try testing with Dynamic or Manual playlists?

**Comment by justinwohl** [comment]
Issue resolved, I made a Dynamic Playlist and it functions

**Comment by justinwohl** [comment]
Thanks John, making a Dynamic Playlist did the trick.

Not to refine that playlist and keep building out the page.
We're likely to redirect to this, if built out nicely, before EOW.


*Justin Wohl *| Director, Operations and Product
