### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by dvdnhm** [jwplayer/jw-showcase#140]
### Expected Behavior

Expecting to see video files related to entered keyword.

### Actual Behavior

Search result page returns empty.

### Steps to reproduce

1. http://media.usssa.com
2. search box on top of the screen.

### Environment

Windows 2008 Server / IIS 
latest showcase version.

**Comment by johnluther** [comment]
You are still using the default sample search playlist ID in your configuration file. You need to replace it with a search playlist ID from your own JW account. It need to be in the "searchPlaylist" parameter of your config.json file.

**Comment by dvdnhm** [comment]
I was using a removed playlistID's ID in the config fixed that part, thanks.

I created a playlist that shows last 99 video files we added and copied the playlist ID into the config file.

When I search for a specific keyword, the search returns all 99 files without any filtering:

I marked the keyword and the irrelevant video file in the screenshot

![image](https://user-images.githubusercontent.com/6667615/27549127-0d74496a-5a69-11e7-9f1e-2f79ef02ed8f.png)

**Comment by johnluther** [comment]
You need to create a Search playlist in your JW Dashboard (Playlists > Recommended > New Recommendations Playlist > Video Search Playlist) and use that ID.

**Comment by johnluther** [comment]
(Sorry, the playlist terminology is not very obvious...)

**Comment by dvdnhm** [comment]
It is working now, thanks

**Comment by johnluther** [comment]
OK, thanks for using Showcase!

**Comment by Gatera** [comment]
Hi,

I am having the same issue whereby the search returns all files within the playlist.
I am unable to find the 'Video Search Playlist', I think the dashboard may have changed. The options I have now are JW Dashboard > Curated Playlists > Create a playlist > Manual or Dynamic.

How can I set the search playlist?

**Comment by pajter** [comment]
Hi @Gatera,

To create a search playlist, instead of JW Dashboard > Curated Playlists, go to JW Dashboard > Recommendations > New Recommendations Playlist > Video Search Playlist.
