### ISSUE TITLE
I installed an ssl certificate to our media server and updated all the file urls with https yesterday.

### ISSUE THREAD

**Issue by dvdnhm** [jwplayer/jw-showcase#141]
### Expected Behavior

Using the file URL as entered on JW Dashboard, without a modification.

### Actual Behavior

the showcase ignores the https and calls the file through HTTP

### Steps to reproduce

1.go to http://media.usssa.com
2. click any video and check the m3u8 path in the network tab

### Environment

Windows 2008 Server / IIS
Latest version.

**Comment by johnluther** [comment]
Showcase uses protocol-relative URLs to prevent mixed content scenarios. If you access using a secure origin, all the assets will be loaded over HTTPS. 

I tried accessing httpS://media.usssa.com/ but got a 404 error.

**Comment by dvdnhm** [comment]
We don't have SSL on the media site and since we are not collecting any information at all, not really necessary.

We play same video files on a different site which has SSL certificate, so the video URLs are https.

I understand your reason, but this way you are taking away the control from us. Which in this case the good intention caused a bad result.

**Comment by johnluther** [comment]
Marking as Enhancement request, we will need to discuss. 

In the meantime, if this is an urgent matter for you, you can modify the code (jw-showcase-lib/js/core/services/api-service.js, the fixUrl function starting at line 245) and [rebuild from source](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code)

**Comment by dvdnhm** [comment]
Thanks.

I was able to swap port 80 between applications on the server to fix the issue.
