### ISSUE TITLE
Facebook Pixel for JWShowcase

### ISSUE THREAD

**Issue by KirthiPriyak** [jwplayer/jw-showcase#144]
### Expected Behavior

Trying to implement facebook pixel for our website for page loads. The media id should be available in vendor javascript files of Version 3.3 . I was able to do this for Showcase 3.1 version but not 3.3

### Actual Behavior

Could not get media id that is getting loaded in the page to send a request for tracking fb pixels. The new addition of vendor1.js and vendor2.js made this complicated. Is there any way I can implement fb pixel for our website. 

This is our website : https://myhealth1stapp.appspot.com/

**Comment by ChristiaanScheermeijer** [comment]
Hi @KirthiPriyak,

I'm not sure how you previously obtained the mediaid, but there are multiple ways to do this. One of them is to use the angular injector outside the angular application, you can use the code below to obtain the current $state information.

```
<script>
var injector = angular.element(document.body).injector();
var state = injector.get('$state');

fbq.track('event', state.mediaid);
</script>
```

Will this help you?

**Comment by KirthiPriyak** [comment]
Hi @ChristiaanScheermeijer , 

Thanks for the help, Somehow adding the ready statement made it work. 

var injector = angular.element(document.body).injector();
var state = injector.get('$state');
angular.element(document).ready(function () {
			var mediaId = state.params.mediaId
			fbq("trackCustom", 'ButtonClick', {mediaid: mediaId});		
});
