### ISSUE TITLE
"You appear to be offline. Retry" page load error

### ISSUE THREAD

**Issue by matthodkinson** [jwplayer/jw-showcase#147]
### Expected Behavior

*JW showcase loads*

### Actual Behavior

*Messaging saying "You appear to be offline. Retry'" shows*

### Steps to reproduce

*1. I followed the steps to download the files and edit the config.json file with the player ID in my dashboard*
*2. I uploaded the files to my server*

### Environment

*- Any browser*
*- Any OS*
*- http://kaleidomatt.com/fiig/*

**Comment by johnluther** [comment]
Somehow the Javascript in the files your /scripts/ directory have been replaced with HTML. For example, http://kaleidomatt.com/fiig/scripts/scripts.js
