### ISSUE TITLE
Support in-video search

### ISSUE THREAD

**Issue by jeroenwijering** [jwplayer/jw-showcase#150]
Search Feeds in JW Platform now support search through closed captions. A list of timecodes is returned per item in the feed if there are matches. Support these in showcase by:

1. Showing a timeline with "dots" on search result cards that have in-video matches.
2. On hovering/touching the card, use thumbstrips to preview location in the timeline.
3. When hovering a "dot", display captions cue at that position in the video.
4. When clicking the video, start at selected offset.

![card-hover](https://user-images.githubusercontent.com/7049474/28569617-d4d0ce10-713a-11e7-940a-0fdb9595e790.png)
![card-out](https://user-images.githubusercontent.com/7049474/28569618-d4d8e5dc-713a-11e7-80c5-60b7dacf3f91.png)

**Comment by ChristiaanScheermeijer** [comment]
This feature is added in v3.6.0!
