### ISSUE TITLE
JWShowcase shared video links won't work

### ISSUE THREAD

**Issue by workmarco** [jwplayer/jw-showcase#154]
Hello team,

I'm having this issue with out jwplayer, I went over JWplayer but they couldn't tell, is there any way you can help me?

Thanks.

Shared links should play when pasted into the url.

Describe expected behavior
The expected behavior should be that a copy and pasted link should play when paste in the browser

Actual Behavior

Describe actual behavior

The copy paste link is not populated when it's copied

Steps to reproduce

go to www.evite.com/videos/
copy and paste a link from a video to share
paste the link into the browser.
Environment

*hardware | Any
*operating system | Any
*browser | Any
*JW Player version | Any

**Comment by ChristiaanScheermeijer** [comment]
Hi @workmarco,

Because you have embedded Showcase into an iframe this will not work directly.

Somehow you will need to sync the iframe URL with your website to be able to refresh. For example, inside the iframe the `document.location.href` will change whenever you navigate to Showcase. I would then use this value to change the parents URL to include a query parameter e.g. www.evite.com/videos/?p=/list/2TlouHeZ/video/RBjATpVi/meowllennials-club-night

**Comment by workmarco** [comment]
Hi @ChristiaanScheermeijer ,

Thanks for your answer and help. I still have a few questions if you don't mind.

1) What you're saying is that I can't have the Showcase hosted in an S3 bucket domain that it's different than the domains of the website?
website: www.evite.com
s3 bucket: partners.evitecdn.com

2) The same link you provided as an example displays the showcase again, that's good, but it doesn't navigate to the specific video I was trying to share, is there some configuration I might be missing?

3) Do you have any ideas on why a direct link to the video with the s3 bucket url gives me an Access Denied errors?, looks like I can only display it if I use the index.html 
https://partners.evitecdn.com/videos/index.html

**Comment by johnluther** [comment]
Hi, @workmarco . It looks like you are trying the iframe approach b/c you have a requirement to use your existing Evite header navigation and footer. 

The better approach for that would be to use your own header and footer templates as described in https://github.com/jwplayer/jw-showcase/wiki/Customizing-JW-Showcase

**Comment by workmarco** [comment]
HI @johnluther ,

Thanks.

The requirement is actually that the video showcase has to appear to be served from a subdirectory of the main website as in https://www.evite.com/videos/ to keep the url and the branding.

Any ideas?

**Comment by johnluther** [comment]
@workmarco Yes, just follow the instructions to add the custom header and footer, rebuild Showcase with grunt, and then upload the files in /dist/ to your /videos/ location. Be sure to follow the instructions in https://github.com/jwplayer/jw-showcase/wiki/Deploying-JW-Showcase to ensure that HTML5 URL rewriting works.

JL

**Comment by treyconnell** [comment]
We're having the same problem here: http://housingwire-stage.epublishing.com/video/

Videos play fine, but when I copy and paste the link to share a video it does not work. Nginx has been modified per the docs:

`location /video/ {
    try_files $uri$args $uri$args/ $uri/ /index.html =404;
  }`

Example video link copied from the sharing option: http://housingwire-stage.epublishing.com/video/list/bx0W6SFX/video/Uq86weCO/cfpb-director-cordray-pens-new-york-times-op-ed-in-effort-to-save-arbitration-rule

**Comment by treyconnell** [comment]
OK, I believe I found the issue. Since the files live at /video/ we need to modify that nginx config. 

`location /video/ { try_files $uri$args $uri$args/ $uri/ /video/index.html =404; }`

Note the /video/index.html
