### ISSUE TITLE
Featured Playlist Off-Center

### ISSUE THREAD

**Issue by john-maxwell** [jwplayer/jw-showcase#16]
### Expected Behavior
On the JWShowcasedemo site, the featured playlist is **centered**.

### Actual Behavior
I'm testing out the new showcase app and my featured playlist is **off-center**.

### Steps to reproduce
Simply loading the site in the browser reveals that it's off center.  It doesn't match the JW demo site.  Am I doing something wrong, or is this how it's supposed to display?  I prefer it to be centered.

### Environment

- OSX 10.11.4
- JW showcase 1.0 / 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Hi, John, thanks for checking out JW Showcase. 

Very sorry about that. You are correct, the design is different. We were testing something for our upcoming 1.1 release later this week. 1.1 will include some UI tweaks (one of them being the centered design). 

I changed the demo site back to the 1.0 codebase.

JL

**Comment by john-maxwell** [comment]
Perfect.  Thanks for the clarification!  I love what I'm seeing so far.  Can't wait to see it developed further.

**Comment by johnluther** [comment]
Cool, thanks, please post Issues for any feedback or feature requests!
