### ISSUE TITLE
Playlist Grid View - Feature Request

### ISSUE THREAD

**Issue by john-maxwell** [jwplayer/jw-showcase#17]
### Expected Behavior
For playlists with large quantities of videos, I'd like to be able to click on the Playlist Title and be taken to a new page that shows a grid view of all the videos in the playlist versus the shelf/carousel.  It would allow for faster browsing of the content.  The current Netflix site is a good example of this functionality

### Actual Behavior

Carousel/Shelf view is the only current display option

### Environment

-MacPro
- OSX
- JW Showcase 1.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Thanks, John. This one is similar to issue #2 . We definitely need some additional view page options.
