### ISSUE TITLE
Top Level Menu - Feature Request

### ISSUE THREAD

**Issue by john-maxwell** [jwplayer/jw-showcase#18]
### Expected Behavior

I would like see a drop-down browse menu that alphabetically displays the titles of all of the playlists embedded in the site.  Clicking on a playlist in this menu would take you to a new page with a grid view of the videos in the playlist.  Or optionally it would scroll down the page to reveal the selected playlist.  This would allow faster browsing of sites that have large quantities of playlists.
### Actual Behavior

Currently no menu or faster way to navigate content.
### Environment
- MacPro
- OSX
- JW Showcase version 1.0 

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by jeroenwijering** [comment]
This is a great idea that can potentially be implemented as a "hamburger menu" on the left side. In addition to replicating the playlist "shelves", it can also host options for e.g. video quality (HD/SD, for mobile devices) and clearing history (for when we introduce Watching / Favorites lists)
