### ISSUE TITLE
Cannot connect to Videos

### ISSUE THREAD

**Issue by EBEL63** [jwplayer/jw-showcase#184]
### Expected Behavior

Installed JWPlayer locally 

### Actual Behavior

Error message: You appear to be offline. Retry

### Steps to reproduce

1. loaded down all files from Github
2. adopted config.json and index.html [showcase.zip](https://github.com/jwplayer/jw-showcase/files/1643435/showcase.zip)

3. installed it on my webserver

### Environment

http://www.erstebankliga.at/jwvideos/ahl/highlights-teams/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by pajter** [comment]
Hi,

It looks like you have a typo in your code. I see that the HTML file is trying to load the files from `http://www.erstebankliga.at/video/ahl/highlights-teams/scripts`.

Try changing it to be `http://www.erstebankliga.at/jwvideos/ahl/highlights-teams/scripts`. You can see that the files are reachable there, eg: http://www.erstebankliga.at/jwvideos/ahl/highlights-teams/scripts/bridge.js.

Let me know if you get it working!

**Comment by EBEL63** [comment]
Hello pajter, thank you, that was definitely an error, but it did not help.

**Comment by ChristiaanScheermeijer** [comment]
must be the browser cache, it is working here!

**Comment by EBEL63** [comment]
You are right - thank you. What a stupid error - but when you look to often to it.....

**Comment by pajter** [comment]
Yeah I know the feeling! :)

I'll close this issue. Let me know if you need any more help.
