### ISSUE TITLE
Mouse over featured videos

### ISSUE THREAD

**Issue by Gatera** [jwplayer/jw-showcase#198]
### Expected Behavior

*Cover image to stay or High res thumbnails on mouse over*

*The thumbnails that show on mouseover are too low Res, is it possible to show only High Res photos or disable the feature?

### Actual Behavior

*Slideshow of low res screenshots on mouse over*

### Steps to reproduce

1. Place mouseover featured video

### Environment

- *Webserver*
- * Apache*
- *JW Showcase v3.9.1 | beta.journal.rw*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by pajter** [comment]
We are aware of this issue, and are investigating higher resolution thumbnail strips. Unfortunately I don't have any timeline for that.

Disabling this behavior is currently only possible for self-hosted Showcases.

**Comment by Gatera** [comment]
Hi @pajter 
Thanks for the explanation, I will keep looking out for an update on that issue.

The Showcase I am using is self-hosted, how can I disable that feature?

**Comment by Gatera** [comment]
It worked. Thanks for sharing the wiki page too!
