### ISSUE TITLE
Error on page reload

### ISSUE THREAD

**Issue by Gatera** [jwplayer/jw-showcase#199]
### Expected Behavior

*Video page to refresh when browser reload button is pressed*

### Actual Behavior

*Page returns 'Internal Server Error'*

### Steps to reproduce

1. Go to beta.journal.rw
2. Play any video
3. Click reload page

### Environment

- * Webserver*
- *Apache*
- *v3.9.1 | beta.journal.rw*

*I have tried the solution on this page https://github.com/jwplayer/jw-showcase/wiki/Deploying-JW-Showcase of inserting the text in a htaccess file. When I place the file in the root folder the whole site does not work. I get a '500 - Internal Server Error'.

The website is located in public_html/beta folder.*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by pajter** [comment]
Hi @Gatera

You're not running it in a subdirectory, so it should be fairly straightforward to set up. Did you change the paths in the `.htaccess` file to your own public_html/beta path?

Have you tried checking your server logs for any messages regarding this 500 error? There's probably something going on with the `.htaccess` file not being parsed properly. It's not something I can see from here though. You'll have to debug that on your server.


Let me know if I can be of help.

**Comment by Gatera** [comment]
Hi @pajter 

I updated the .htaccess file the following way:

<VirtualHost *:80>
  ServerName beta.journal.rw
  DocumentRoot /public_html/beta
  <Directory /public_html/beta>
    <ifModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule (.*) index.html [L]
    </ifModule>
  </Directory>
</VirtualHost>

and the server logs returned the following:

- - [18/Jul/2018:16:23:05 +0200] "GET / HTTP/1.0" 500 1862 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:61.0) Gecko/20100101 Firefox/61.0"


but I still get the same '500 - Internal Server Error'

**Comment by pajter** [comment]
The `.htaccess` file looks okay to me. Your server log line seems like it's from the access instead of the server log. The 500 error would probably get dumped somewhere else. Maybe it's related to a missing or disabled Apache `mod_rewrite` module.

**Comment by Gatera** [comment]
Could this be the error log?

[Wed Jul 18 16:23:05.196833 2018] [core:alert] [pid 30024] [client 105.178.112.19:55840] /home/stjourna/public_html/beta/.htaccess: <VirtualHost not allowed here

**Comment by pajter** [comment]
Yeah that's the one. Seems your Apache configuration does not like that `.htaccess` override. You could try putting the contents of that VirtualHost block into your Apache vhost config file instead of in the `.htaccess`.

**Comment by Gatera** [comment]
I just tried something that worked. I was looking at the .htaccess file I have in my /public_html folder where I am running Wordpress. It starts from <ifModule mod_rewrite.c> and ends with </ifModule>.
So I deleted everything else and only kept the following:

<ifModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule (.*) index.html [L]
</ifModule>

and it works!

**Comment by pajter** [comment]
Good to hear! 👍

**Comment by Gatera** [comment]
Thanks for your help
