### ISSUE TITLE
Event tracking?

### ISSUE THREAD

**Issue by jguerine** [jwplayer/jw-showcase#201]
Hello,
Are there any events that could be used for some customized tracking, or should we just code our own?

Thanks !

**Comment by pajter** [comment]
Hi,

Unfortunately we do not currently support any custom events system.

Best

Pieter

**Comment by jguerine** [comment]
Hello @pajter ,

So does that mean that it's not possible to add any custom code allowing to do that?
I've been working on some tracking, and it does work for the first page. But then it doesnt really work while navigating through the platform.
I've tried working on event propagation, but not a single class / item seems to allow me to attach a click event.

So, does that confirm what you were saying yesterday, that it's not possible AT ALL to add custom  clicktracking?
Will it evolve?

Thanks

**Comment by pajter** [comment]
Hi @jguerine,

If you're building Showcase from source, there's always a possibility to add custom tracking code. A good place to start would be the router. It's implemented per module. Here's an example for the [dashboard module/page](https://github.com/jwplayer/jw-showcase/blob/develop/app/scripts/dashboard/dashboard.module.js#L33).

However, if you're just using the prebuilt version, there's only so much you can do to. It's possible in theory to add click event listeners to buttons, but this would be quite cumbersome to implement and not foolproof at all.

So no, we don't have an easy way or configuration option to integrate custom clicktracking. There are also currently no plans to add this.

Pieter

**Comment by jguerine** [comment]
Thanks for the explaination. We found a workaround with a dev

**Comment by pajter** [comment]
Great!

**Comment by jguerine** [comment]
Hey, quick question : so I am guessing that regarding the tracking of the plays/pause etc from the actual player, it's also something that may be custom on our side?

Thanks
