### ISSUE TITLE
Icon font not working

### ISSUE THREAD

**Issue by chzr** [jwplayer/jw-showcase#21]
### Expected Behavior

Icomoon font should show across all browsers

### Actual Behavior

Icomoon font is not showing across multiple devices it only works on chrome

### Steps to reproduce

Solution for me: https://css-tricks.com/forums/topic/font-face-icon-font-not-working-in-firefox/

### Environment

- *iMac*
- *OSX El capitan | nginx local server*
- *JW Showcase version : 1.1.0*

----------------------------------------------------------------------------------------

**Comment by johnluther** [comment]
Thanks, chzr. I wasn't able to reproduce this. 

Specifically which browsers and devices were the fonts not showing? Can you provide any screenshots of the behavior or developer console error output from browser?

JL

**Comment by ChristiaanScheermeijer** [comment]
@chzr which particular fix did you used? Adding the 'Access-Control-Allow-Origin: *' header or removing the query parameter from the font-face url?

**Comment by chzr** [comment]
@johnluther @ChristiaanScheermeijer  I wasn't able to see the icons on firefox and ios and the solution for me was removing the query parameter from the font-face url
