### ISSUE TITLE
Sharing video is not using correct url

### ISSUE THREAD

**Issue by tariqinaam** [jwplayer/jw-showcase#22]
### Expected Behavior

As a user when I share a video, it should share that particular video url on twitter and facebook

### Actual Behavior

When i share any video, it simply share root url only.

### Steps to reproduce

1. visit jwshowcase site
2. click on any video
3. click share twitter link
4. share url is base url

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Thanks, tariqinaam. I was able to reproduce this. The demo site is running our 1.1 Beta, perhaps we have a regression, we will take a look.
