### ISSUE TITLE
"Failed to Load Config File"

### ISSUE THREAD

**Issue by pwslavish** [jwplayer/jw-showcase#28]
### Expected Behavior

Updating the config.json with revised Player & Playlist IDs to update the Showcase contents

### Actual Behavior

Get an error screen "Failed to load config file"

### Steps to reproduce

1. Update the config.json with revised playlist IDs
2. Upload the files to S3
3. Go to URL http://roguemoney.tv.s3-website-us-east-1.amazonaws.com

### Environment

- *Macbook Late 2013*
- *OS El Capitan 10.11.6*
- *JW Showcase version 1.1.0 | http://roguemoney.tv.s3-website-us-east-1.amazonaws.com*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
It looks like you got curly "smart" quotes in your config.json file in the theme line when you changed it from the default light to dark. JSON requires straight quotes.

Your line 3 is: "theme": “dark”,

It should be: "theme": "dark",

Note the difference in quotes around "dark".

What text editor did you use to modify the config file? You appear to be on a Mac, try the built-in Textedit program in the /Applications folder.

JL

**Comment by johnluther** [comment]
And make sure in the TextEdit preferences the Format is set to Plain Text, not Rich Text.

**Comment by pwslavish** [comment]
That worked! Thanks so much John, appreciate the help.  Had to go into EDIT>>SUBSTITUTIONS within TextEdit to un-check the smart quotes and smart dashes to prevent it from auto-"correcting" anytime I typed something or updated lines.

**Comment by johnluther** [comment]
Cool, glad to help!

JL
