### ISSUE TITLE
Make it easier to include custom headers and footers

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#3]
### Expected Behavior

As a publisher, I expect it to be simple for me to include my own custom headers and footers in a Showcase app.
### Actual Behavior

I am required to hack the View templates in the Angular source code and then build the app with grunt.
### Steps to reproduce

Not applicable
### Environment
- _hardware | device_
- _operating system | version_
- _JW Showcase version | url_

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by jeroenwijering** [comment]
Is it possible to include a header and footer in the index.html, that is dynamically pulled into the Showcase app? That would definitely make it easy to edit. Or include separate header.html and footer.html files in the deploy?

**Comment by johnluther** [comment]
@jeroenwijering Yes, this is possible using Angular's ng-include directive. Things can get tricky, though, if there are CSS style name conflicts with Showcase, a DIV gets out of place, etc. 

https://docs.angularjs.org/api/ng/directive/ngInclude

**Comment by jeroenwijering** [comment]
Agreed that can be tricky. Maybe we need a few styled header / footer elements, e.g. taking our own tv.jwplayer.com as example. I do anticipate many customer wanting their own header/footer though (case in point just our own site).

**Comment by ChristiaanScheermeijer** [comment]
All templates can be overridden (also when using the precompiled version) by adding `<script type="text/ng-template"></script>` blocks in the index.html.

If you want to customise the footer you can add this in the index.html

```
<script type="text/ng-template" id="views/core/footer.html">
  <div class="jw-footer">
    <p>Now the footerText is not used from the config.json</p>
    <p>But you can use angular syntax: {{ ::vm.config.footerText }}</p>
  </div>
</script>
```

I think this brings more than enough possibilities to customise the header and footer in JW Showcase, do you agree?

**Comment by johnluther** [comment]
Yes, that is probably a better short-term solution than nginclude for basic customization, thanks. We should document it in the wiki.

As for hosted Showcases, ideally we want to have some templates that users can populate, but in the medium-term we could allow them to paste some HTML into header and footer fields in the UI and override the templates with that HTML.
