### ISSUE TITLE
JW Showcase Sharing Features 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#32]
### Share on Facebook and display the video title and video description. 

*When you share the video it should display the title and description of the video that you have chosen to share. *

### "Page not found" and the same video title and description appear for every video. 
Link to website: http://cntvnow.com/testing/

### Steps to reproduce

1. click share and facebook
2. do this for every video, the description and title do not match the video nor does it change.

**Comment by johnluther** [comment]
@akashpatel0427 , thanks for using Showcase.

Make sure your web server is configured for html5Mode (pretty URLS). See https://github.com/jwplayer/jw-showcase/wiki/Deploying-JW-Showcase for instructions.

JL

**Comment by akashpatel0427** [comment]
Where is the .htaccess file I can not locate it in the precompiled code?
and I can see it on my FTP site but once i download it, i cannot locate it on my computer

**Comment by johnluther** [comment]
Because the filename starts with a dot, your local system is probably treating it as a system file and thus hiding it.

If you are using Windows, see this: https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files

If Mac, click File > Open in your text editor, then press Command+Shift+Period to view hidden files.

JL

**Comment by akashpatel0427** [comment]
Do I copy and paste the example given into the .htaaccess file. Also is there a .htaccess file in the precompiled JW showcase file or do i modify the .htaccess on my actual website across all my websotes. Sorry

**Comment by johnluther** [comment]
There is one in the precompiled app. If your Apache server is running in the default location (/var/www), just change the <Directory> path to /var/www/testing/.

If it is in a non-default location, add /testing/ to whatever the path is.

**Comment by akashpatel0427** [comment]
# BEGIN (mt) controlled settings
<IfModule !mod_fcgid.c>
  AddHandler php-stable .php
</IfModule>
<IfModule mod_fcgid.c>
  AddHandler fcgid-script .php
  FcgidWrapper /etc/apache2/gs-bin/php-stable-wrapper .php
  <Files *.php>
    Options +ExecCGI
  </Files>
</IfModule>
# END (mt) controlled settings

# Redirect old file path to new file path
Redirect /category/videos/ceir-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect /category/videos/iaee-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect video.theexhibitionschannel.com/pages/iaeetv.html http://www.theexhibitionschannel.com



Ok so here is the real apache, and the link to this website is http://www.theexhibitionschannel.com/
this lives in the root folder. The example I provided earlier was for a testing website. I rather work with the real thing.

**Comment by akashpatel0427** [comment]
`# BEGIN (mt) controlled settings
<IfModule !mod_fcgid.c>
  AddHandler php-stable .php
</IfModule>
<IfModule mod_fcgid.c>
  AddHandler fcgid-script .php
  FcgidWrapper /etc/apache2/gs-bin/php-stable-wrapper .php
  <Files *.php>
    Options +ExecCGI
  </Files>
</IfModule>
# END (mt) controlled settings

# Redirect old file path to new file path
Redirect /category/videos/ceir-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect /category/videos/iaee-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect video.theexhibitionschannel.com/pages/iaeetv.html http://www.theexhibitionschannel.com`

**Comment by johnluther** [comment]
Is this a Wordpress site?

**Comment by akashpatel0427** [comment]
Some of it is on wordpress some of it is FTP, I access is both ways through file zilla and wordpress.

**Comment by johnluther** [comment]
OK. Is the .htaccess file you pasted above from the wordpress server or ftp?

**Comment by akashpatel0427** [comment]
FTP site

**Comment by johnluther** [comment]
Okay, @ChristiaanScheermeijer , can you take a look at this?

**Comment by nvang** [comment]
Hi, can you try using the provided .htaccess or add the showcase htaccess to your existing file? It seems your provided htaccess is missing the showcase part.

**Comment by akashpatel0427** [comment]
Hi I used the precompiled zip on the website was it not inside there? If so where can I find it?

**Comment by johnluther** [comment]
The file is in the Zip but your system is still not seeing it due to the dot (see solution for that in my previous comment). 

I don't want to break anything on your server if that old .htaccess is needed, so try this new one:

# BEGIN (mt) controlled settings
<IfModule !mod_fcgid.c>
  AddHandler php-stable .php
</IfModule>
<IfModule mod_fcgid.c>
  AddHandler fcgid-script .php
  FcgidWrapper /etc/apache2/gs-bin/php-stable-wrapper .php
  <Files *.php>
    Options +ExecCGI
  </Files>
</IfModule>
# END (mt) controlled settings

# Redirect old file path to new file path
Redirect /category/videos/ceir-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect /category/videos/iaee-tv http://www.theexhibitionschannel.com

# Redirect old file path to new file path
Redirect video.theexhibitionschannel.com/pages/iaeetv.html http://www.theexhibitionschannel.com

# Needed for the AngularJS html5 routing option. The following rewrite makes
# sure we don't see 404 pages when navigation to routes directly.
<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.html [L]
</ifModule>

**Comment by akashpatel0427** [comment]
NEED HELP URGENT. 

I used that .htaaccess file and it still does not work, but i cannot share my link with any one, say i click a video and copy the url to send in an email the page is not found!! THIS is an URGENT issue. thank you .

**Comment by johnluther** [comment]
Try using just this in the .htaccess:

```
<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.html [L]
</ifModule>
```

**Comment by akashpatel0427** [comment]
Nothing still the same error,

**Comment by akashpatel0427** [comment]
Can I get rid of the .htaccess all together?

**Comment by akashpatel0427** [comment]
I got a 404 error, even after removing, my clients are itching for the link

**Comment by johnluther** [comment]
No, the .htaccess file is required.

Do you have an Apache server administrator who can look at this? There might be something in your Apache configuration that is overriding the .htaccess settings.

**Comment by akashpatel0427** [comment]
I do not, do you have any suggestions or anything I could do?

**Comment by johnluther** [comment]
Where is this Apache server hosted? Do you have access to it's configuration files, or just ftp access to the document root?

**Comment by akashpatel0427** [comment]
Well I am not entirely sure, I have access to the FTP. I would hope the apache is stored on my server. cntvnow.com

**Comment by johnluther** [comment]
Without knowing more about how your web server is set up, it's difficult for me to know what is going one. Who administers your cntvnow.com site?

**Comment by akashpatel0427** [comment]
I GOT IT I think!!!

**Comment by akashpatel0427** [comment]
I got it!! 
Thank you so much

**Comment by akashpatel0427** [comment]
I was not putting the .htaccess inside the showcase files. it was outside

**Comment by johnluther** [comment]
Great, seems to be working for me.

It looks like you are running Showcase 1.0. I recommend updating to 1.1, there are some important fixes in 1.1

https://github.com/jwplayer/jw-showcase/releases/tag/v1.1.0

**Comment by akashpatel0427** [comment]
Great, would i have setup from scratch like the favicons, and the title and playlists or can i update to 1.1 a lot faster?

**Comment by johnluther** [comment]
Just copy the 1.1 files to the ftp server and overwrite the 1.0 files.

EXCEPT, **don't** overwrite these files:

config.json
images/logo.png
favicon.ico

JL

**Comment by akashpatel0427** [comment]
Thank you so much, sorry for all the trouble. You really helped me out. My clients will be so happy

**Comment by johnluther** [comment]
Glad to hear it, my pleasure. Thanks for using Showcase and JW Platform!
