### ISSUE TITLE
Says failed to load config file when going to the site

### ISSUE THREAD

**Issue by dwhitley** [jwplayer/jw-showcase#36]
### Expected Behavior

*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1. just open website 
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | http://www.bethelumcatlanta.org/video/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by nvang** [comment]
Hello @dwhitley, there are encoding errors in your config.json file:
http://www.bethelumcatlanta.org/video/config.json

The " character is replaced with a wrong character. Which OS are you on so we can suggest a text editor to fix this.

**Comment by dwhitley** [comment]
here is a copy on my config file and i'm using a mac 

{
    "player": “oTEiLra8”,
    "theme": "light",
    "siteName": “Bethel United Methodist Church TV”,
    "description": "JW Showcase is an open-source, dynamically generated video website built around JW Player and JW Platform services. It enables you to easily publish your JW Player-hosted video content with no coding and minimal configuration.",
    "bannerImage": "images/logo.png",
    "footerText": "Powered by JW Player",
    "backgroundColor": "",
    "featuredPlaylist": “3lt619Ww”,
    "playlists": [
        "3lt619Ww”,
        "Q352cyuc",
        "oR7ahO0J"
    ]
}

**Comment by nvang** [comment]
E.g. for player “ is used instead of ". This often happens when using a rich text editor.

Below should be correct 

```
{
"player": "oTEiLra8",
"theme": "light",
"siteName": "Bethel United Methodist Church TV",
"description": "JW Showcase is an open-source, dynamically generated video website built around JW Player and JW Platform services. It enables you to easily publish your JW Player-hosted video content with no coding and minimal configuration.",
"bannerImage": "images/logo.png",
"footerText": "Powered by JW Player",
"backgroundColor": "",
"featuredPlaylist": "3lt619Ww",
"playlists": [
"3lt619Ww",
"Q352cyuc",
"oR7ahO0J"
]
}
```

**Comment by dwhitley** [comment]
thanks that worked what a good editor to use

**Comment by ChristiaanScheermeijer** [comment]
Hi @dwhitley,

You could use [Sublime text](https://www.sublimetext.com/3) which is compatible with OS X, Windows and Ubuntu.

It is also possible to change your keyboard settings (e.g. if you are using OS X in `System Preferences -> Keyboard -> Text`. Change the `For double quotes` option from `“abc”` to `"abc"`).

Thank you for using JW Showcase!
