### ISSUE TITLE
Embed and Share Link Option. 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#37]
### Expected Behavior

*When you press the share button you should get an option like in the regular JW player to share the link or email the link or even embed the code/player on your own website. *

### Actual Behavior

*When you press share you only see Twitter and Facebook no direct link to the video to share to a person via email. *

### Steps to reproduce

1. Click share and notice only two share options on the player. 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Agree, we should add a direct link option w/ icon.

**Comment by ChristiaanScheermeijer** [comment]
_1. Click share and notice only two share options on the player._

@akashpatel0427 Where do you 'Click share'?

**Comment by akashpatel0427** [comment]
I dont click share when you hover over the video you only see facebook and twitter you dont see an option to embed or share the link to that specific video.

**Comment by ChristiaanScheermeijer** [comment]
Ok, just to make sure we are talking about the same thing :-)

**Comment by akashpatel0427** [comment]
Yes no problem. This is not so urgent the post I created about the thumbnail is more urgent are you able to help me out with that first?
