### ISSUE TITLE
Feature request: Make a difference between LIVE and VOD video's in dashboard

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jw-showcase#40]
### Expected Behavior

As a user I want to see if a video is a live stream. Perhaps show `LIVE` (online/offline) instead of the duration label. 

![image](https://cloud.githubusercontent.com/assets/3996119/18124012/c7fc88d6-6f70-11e6-8112-adefe81ed348.png)
### Actual Behavior

Users don't see the difference between VOD and LIVE video's and duration label shows `0 sec` for live streams.

![image](https://cloud.githubusercontent.com/assets/3996119/18123998/b7de962e-6f70-11e6-8726-792852a691f5.png)
### Steps to reproduce
1. Add a live stream to playlist
2. Open JW Showcase
### Environment
- _JW Showcase v1.1.0_

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
I think this would be a good enhancement, provided that you can always assume that a 0 second duration means a live stream.

**Comment by ChristiaanScheermeijer** [comment]
This is also added in 3.0.0
