### ISSUE TITLE
Render MicroData tags for video's

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jw-showcase#41]
### Expected Behavior

Render MicroData tags with video metadata

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
@ChristiaanScheermeijer , can you give me a bit more context on this one?

**Comment by ChristiaanScheermeijer** [comment]
@johnluther yes sure :-), we should add the SEO metadata which you can also add using the JW Dashboard (checkbox in embed video view).

Example:

```
<div itemscope itemtype="http://schema.org/VideoObject">
<meta itemprop="uploadDate" content="2016-08-31T16:17:22+0200" />
<meta itemprop="name" content="{{ videoTitle }}" />
<meta itemprop="contentUrl" content="{{ videoUrl }}" />
```

**Comment by johnluther** [comment]
Got it, thanks.

**Comment by johnluther** [comment]
Some best practices tips at https://developers.google.com/webmasters/videosearch/schema
