### ISSUE TITLE
Time delay in publication

### ISSUE THREAD

**Issue by angelcasana** [jwplayer/jw-showcase#44]
Hello: I'm creating a video site ( http://socialvideo.es/investingvdo/ ) and everything was right. But now, the playlists are not showing the videos tagged for that playlists. 

At some point, without rewrite or change the config.js, site stopped to show new videos. 

The playlist in JW player dashboard show the correct list of videos for that specific playlist that should be showing in the site. 

Can somebody help me. Thank you in advance.

**Comment by johnluther** [comment]
Hi, Angel. The videos and play lists are working for me. Are you still
seeing the problem?

**Comment by angelcasana** [comment]
Hi John, thank you. Yes, is working now. There's a reason to see some delays between time to publish in JW Player dashboard and see it in the site?

**Comment by angelcasana** [comment]
Hi, I'm experiencing delays since I upload a video to JW Player until it is published on the website. Even it spend hours between the two steps.

**Comment by johnluther** [comment]
That is unusual. Unless they are extremely long, videos usually process
within minutes.

Can you open a case with support@jwplayer.com

**Comment by angelcasana** [comment]
Ok, I'll do it. Thank you

**Comment by DolandJW** [comment]
I'm thinking the page is being cached by the browser. We've received your ticket and I will update this page when we get some more information.

**Comment by angelcasana** [comment]
You were right, it was a cache problem. Thank you
