### ISSUE TITLE
Investigate support for federated logins

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#49]
### Expected Behavior

As a user, I want my watchlist, "continue watching" videos and other Showcase settings to sync across my browsers and devices.

As a publisher, I want to offer additional features and services that are only possible when users are logged in. For example, show or hide particular playlists depending on whether the user is logged in, share directly to Facebook w/o a log in step, etc.

The Showcase login solution must adhere to relevant privacy laws and regulations.

Amazon Cognito could be a good solution but we should research others.
### Actual Behavior

Watchlist and continue watching lists are only saved on the user's current browser, they do not sync across browsers or devices.

**Comment by ChristiaanScheermeijer** [comment]
@johnluther are you sure this is for 3.1?

**Comment by johnluther** [comment]
Changed the title to "Investigate." We should do the necessary research and formulate a plan in Q1, then implement in Q2.
