### ISSUE TITLE
Showcase not serving preroll

### ISSUE THREAD

**Issue by angelcasana** [jwplayer/jw-showcase#53]
I have set a preroll code in the JW Player dashboard and is not working.

http://investingvdo.com/

Does somebody experienced same problem? Any solution?

Thank you in advance

**Comment by ChristiaanScheermeijer** [comment]
Hi @angelcasana,

You are still using the default player key in the config. When you change this value to your own player key it will play the prerolls.

**config.json**
```
{
    "player": "DTYxzkKG"
    ....
```
