### ISSUE TITLE
Random "rootScope" error.

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#54]
![1](https://cloud.githubusercontent.com/assets/4965317/18601547/4811f854-7c18-11e6-9cd8-d134a84ce224.png)

This error happens infrequently and randomly as I'm watching videos on http://moviepilot.com/video.

**Comment by ChristiaanScheermeijer** [comment]
I will look into this

**Comment by ChristiaanScheermeijer** [comment]
This is related to #57 and will be fixed by 315f6042.
