### ISSUE TITLE
Provide config option to disable Continue Watching shelf

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#56]
Some publishers might not want to use the Continue Watching feature. We should provide a config option for disabling it and hiding its thumbnail shelf.

**Comment by johnluther** [comment]
Another refinement could be to only show the last watched video in first position of the Jumbotron

**Comment by YoeriLaros** [comment]
I've implemented this in the design now. Maybe we should also provide an option for users to select which category is being displayed in the hamburger menu (their favorite categories, so to speak). So main page shows all categories, but hamburger menu only shows a personal selection of categories, like a shortcut (or quick select). Wat are your thoughts on that?
