### ISSUE TITLE
Unable to Refresh or Resume the Content video

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#57]
When I click to resume watching a video on http://moviepilot.com/video/ I get the ad to play but the content video never starts. I can see the player is buffering the content video but no matter where I click on the timeline I can't get it to resume playback again.

**Comment by darjanmilojkovic** [comment]
This URL in particular is causing a lot of issues: http://moviepilot.com/video/video/PxaUNgms/JwnlxRWt

The application breaks when I refresh to watch the video again on Chrome Version 53.0.2785.116 (64-bit) and Mac OS El Capitan version 10.11.6.

**Comment by ChristiaanScheermeijer** [comment]
Hi @darjanmilojkovic,

This should be fixed by the commit above. It will be included in the final 2.0 release. 

Thank you for reporting this issue!

**Comment by darjanmilojkovic** [comment]
@ChristiaanScheermeijer Thanks for working on it!
