### ISSUE TITLE
Sharing Button 2.0 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#66]
### Share the video via email or link. 

*Button is not present on the bottom bar*

### The button is on the JW showcase demo site but not in the precompiled zip file. 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by akashpatel0427** [comment]
When I download the latest release there is no index.html there are only a few files.

**Comment by johnluther** [comment]
Are you downloading from https://github.com/jwplayer/jw-showcase/releases/tag/v2.0.0? I just tested the precompiled Zip and all the files are there, and the email share button appears.

**Comment by akashpatel0427** [comment]
I had to redownload my computer was acting a little funny, sorry for the false alarm. 

Thank you
