### ISSUE TITLE
Banner Image Very Tiny

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#67]
### Banner image should be the same size as: http://www.theexhibitionschannel.com/

*The banner is very tiny, even though the dimensions of the banner are 1100 x 210 : http://cntvnow.com/gallery/*

### Steps to reproduce

1. Navigate to http://www.theexhibitionschannel.com/
2. compare to , http://cntvnow.com/gallery
3.

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

In the latest version we've added a back button in the header which is visible on the Feed page. Because of this (and future plans) the heading will always reserve this 'space' on the left and right side of the logo. 

With a small CSS change this can be overruled though.

**Comment by akashpatel0427** [comment]
Any hints on what to change in the code? Thanks.

**Comment by akashpatel0427** [comment]
I changed some things in the CSS however its still smaller than my previous site. On mobile and desktop its smaller than my previous one..

**Comment by ChristiaanScheermeijer** [comment]
If you want the logo to use the full width (like in previous version) you can override the CSS rules of `.jw-header-nav`.

For example:
```
.jw-header-nav {
    -webkit-flex: 0 1;
    flex: 0 1;
    -webkit-align-self: center;
    align-self: center;
    min-width: 0px;
    font-size: 2rem;
}
```

It does look a bit weird on the 'feed' page though (back button not aligned).

**Comment by ChristiaanScheermeijer** [comment]
Ps. I recommend using a separate CSS file for modifications to the precompiled app. So you can still update to the latest minor/bugfix releases without remaking the adjustments to the `main.css` file.

Make file called `styles/custom.css` and add a link tag in the index.html below the `main.css` link tag.

```
<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="styles/custom.css">
```

Now you only have to repeat the last step after each update.

**Comment by akashpatel0427** [comment]
If i do it the CSS way does not seem to work.

**Comment by ChristiaanScheermeijer** [comment]
Ah, you've used the snippet directly. That doesn't work because of CSS priorities (i.e. which rule is more importent). You can fix this by using exactly the same selector as the original.

```
.jw-header .jw-header-nav {
    -webkit-flex: 0 1;
    flex: 0 1;
    -webkit-align-self: center;
    align-self: center;
    min-width: 0px;
    font-size: 2rem;
}
```

**Comment by akashpatel0427** [comment]
I am sorry please excuse my lack of  comprehension. I add the snippet you provided into the custom.css correct? And I leave the main.css exactly like it came from the precompiled-app. And finally to link the stylesheet to custom.css into the code I add it into the index like you explained. Right?? 

<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="styles/custom.css">

**Comment by akashpatel0427** [comment]
`<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="styles/custom.css">`

**Comment by ChristiaanScheermeijer** [comment]
Yes, that is correct. Add the two following overrides in the `custom.css` file to make the logo even bigger:

```
/* allow the logo to cover the header height */
.jw-header .jw-header-logo img {
  max-height: 100px;
}

/* remove the padding */
.jw-header {
  padding: 0;
}
```
