### ISSUE TITLE
Logo doesn't update

### ISSUE THREAD

**Issue by monibons** [jwplayer/jw-showcase#70]
### Expected Behavior

When modifying the static-precompiled-app, replacing the logo.png file in the images folder should update the logo in the header.

### Actual Behavior

The logo remains what it was prior to being replaced.

### Steps to reproduce

1. Create a new logo file named "logo.png"
2. Replace the default logo.png file with the new logo.png file.
3. Observe that the header still shows the old logo.

### Environment

- Mac
- Chrome
- 2.0.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
I couldn't reproduce this. 

However, when I replaced the logo I had to refresh my browser twice to see the new one. Are you sure your old logo wasn't cached in your browser?

**Comment by monibons** [comment]
Ah indeed it was cached. Is there any way that we can force a cache clear for this? I was made aware of this from someone demo-ing to a client and the logo didn't update.

**Comment by johnluther** [comment]
@ChristiaanScheermeijer , please see @monibons question.

**Comment by ChristiaanScheermeijer** [comment]
The easiest option would be to use a different filename for the logo. I
always have my cache turned off in Chrome Dev Tools.
