### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by Dean-Coakley** [jwplayer/jw-showcase#73]
Are there any current plans to port to Angular 2? I know it would require (essentially?) a complete rebuild but people are throwing around 250% - 500% performance increases among other benefits.

**Comment by johnluther** [comment]
Hi, Dean. It's something we've discussed for 2017 but haven't made any solid plans yet. As you point out, it will require a lot of engineering work.

**Comment by ahmadarif** [comment]
Please create jwplayer component for Angular 2/4/5/6 👍
