### ISSUE TITLE
I don't want 'Next Up' to show videos that are not in the playlist.

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jw-showcase#74]
### Expected Behavior

Playing videos from 'Next Up' should be available in JW Showcase. If I define a single playlist in JW Showcase with 5 video's, I don't want 'Next Up' to show videos that are not in the playlist.
### Actual Behavior

Currently JW Showcase will play the 'Next Up' video, but cannot update the url and share links.  
### Steps to reproduce
1. Create JW Showcase with one playlist (assuming there are more)
2. Watch a video from that playlist
3. Click a video in the Next Up overlay which isn't in the selected playlist.
### Environment
- _JW Showcase 2.0_

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
@franklind  and @jeroenwijering , you can see an example of this on my test site: http://jluther.net/videos/

It creates a problem for Showcase b/c after playing a Next Up video that isn't in the playlist, we can't use that video's ID to get the link, title, etc. from the playlist JSON.

JL

**Comment by johnluther** [comment]
It can also potentially confuse users b/c they might expect the Next Up video to be the next video in the shelf, not a recommendation (which might not even be a video from any of the Showcase's configured shelves).

**Comment by jeroenwijering** [comment]
In that case, we should disable recommendations in the player, and only show the recommendations as a shelve above or below the playlist shelve. 

If you  feed the playlist in the player, the "Next Up" overlay will display the next item in the playlist.

**Comment by franklind** [comment]
Agree that we should only expose recommended content in the shelf then (though its below the fold which might mean low interaction) rather than in player. We just want to be sure that we are updating that shelf with a fresh call to the API for every new video to get the best recs.
