### ISSUE TITLE
Create human-readable, SEO-friendly video URLs

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#75]
### Expected Behavior

URLs in Showcase apps should be human-readable to improve UX and search engine indexing. 
### Actual Behavior

Current version of Showcase uses a combination of the playlist ID and video ID to construct URLs. For example, http://tv.jwplayer.com/video/YjQP6aMS/JK30s2i5.
## Solution

The ideal scheme would be lower-case, truncated, hyphen-separated strings based on the playlist title and video title. For example, the example URL above would become http://tv.jwplayer.com/video/jw-insights-2016/analytics-for-revenue-growth.

**Comment by ChristiaanScheermeijer** [comment]
Is this already planned?

**Comment by johnluther** [comment]
Not planned, I would like to do it in Q1 next year.
