### ISSUE TITLE
help Please: Playlist menu or Related Videos not showing up on my site

### ISSUE THREAD

**Issue by eaflix** [jwplayer/jw-showcase#77]
### Expected Behavior

on JW player Tv within the video playing if is  the playlist  the menu bar on right appears as well as the next videos and list of videos in playlist 

### Actual Behavior
on my site http://www.elibtv.com/
the page only shows more video on bottom of the video playing
but not next videos or related 

### Environment

It doest work on any device 
- *JW Showcase  2.0
http://www.elibtv.com/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Hi, @eaflix , thanks for writing and for using Showcase.

if I understand your question correctly, you are trying to use JW Recommendations with Showcase. Recommendations are only supported in the Enterprise edition of JW Player, and with videos that are hosted in JW Platform. If you want to upgrade your account, please contact us at https://www.jwplayer.com/contact-us/
