### ISSUE TITLE
Hide video description text when mouse cursor is not over video viewport

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#8]
### Expected Behavior

If I move my mouse cursor outside the player viewport, I expect the video description to  disappear until the cursor moves back inside the player.

### Actual Behavior

Text stays on the screen for five seconds, then disappears.

### Environment

- Macbook Pro Retina
- OS 10.11.5
- 1.0, http://www.insomniak.se/video/FhLnxXEd/hr1UE5mY

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Should the video description hide simultaneously with the controls of JW Player?

**Comment by johnluther** [comment]
Yes, I think that would be a good way to handle it.
