### ISSUE TITLE
Add support for comments under description box for videos

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#81]
Can we integrate Facebook and/or Disqus comments for the video pages?

**Comment by johnluther** [comment]
Until we see greater demand for this, I think we should document how a customer can integrate one of the many Angular commenting modules (Disqus, Facebook, etc.) in their code.

**Comment by ChristiaanScheermeijer** [comment]
https://github.com/jwplayer/jw-showcase/wiki/Add-Disqus
