### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by MusicTV** [jwplayer/jw-showcase#84]
### Expected Behavior

Hi, our developer is looking for assistance in making customizations for us. Listing the updates under 'describe expected behavior'
 
*Describe expected behavior*

Home Screen

- On the home screen, the filters (tint), film descriptions, and
film titles can all go. Our graphics are eye catching, and self-explanatory; once we remove the tint and words I believe they'll "pop", really grabbing a viewer's attention.

- Playlists - on the home screen, we'll stick with the large graphics -- the film arts we've loaded into JW Player. Right now we're showing five of these - we'll want to add the additional two, for now, and
as we expand our catalog we'll add new entries here as well. Let's go ahead and take the additional graphics, everything under "Wu Tang Saga", leaving just the larger graphics on this page. 

- We can replace "Powered by Legends TV" with "C 2017 Legends Media Group, Inc."

Video Screen

- Let's change the background color, the color behind the description text, from gray, to black. 

- Playlists displayed at the bottom of the screen - it looks as if our Miley Cyrus playlist is anchored at the bottom of several of the video pages. Let's make sure we're showing the proper playlists here, and let's
use the text "Up Next" in place of the playlist title here.

- Share links - I really like the way the AddThis tool works for us on the desktop site - when a viewer makes a post to a social network, a graphic appears, along with the Title, description, and a message
encouraging folks to view the title. Let's go ahead and use the tool to make the same posts from mobile sharers.

Menu Tab

- Let's go ahead and remove the titles from the Menu tab. We'll be adding films, and the space here already looks a bit jumbled with all of the text. Let's clean this up.

- I'd like to add three new pages to the menu tab - Sign In, Terms of Use, and Privacy Policy. We'll be using the same text from the Terms of Use and Privacy Policy displayed on our desktop site. 

General Site Updates

- I'm seeing commercials at odd places throughout our video playback - if you could double check and verify that the right ad schedules are being paired with playlists, I think we can figure this pretty easily. 

- Metadata - It looks like JW Platform uses a standard marketing
statement in its metadata, which is great, and we want to customize it
before sharing the site on the web. I'll draw up some text for you. 

### Actual Behavior

*Describe actual behavior*

Our developer is looking for assistance making these customizations.

### Steps to reproduce

1. visit www.legendstv.com from any mobile device

### Environment

- *hardware | device*

i'm using Safair on an iPhone 5

- *operating system | version*

iOS 

- *JW Showcase version | url*

I believe we're using the most up to date version. 
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by josiekeller** [comment]
Hi there,

Please see our developer guide for instructions on configuring and building your Showcase app in a way that will let you add your own customizations: https://developer.jwplayer.com/jw-platform/docs/developer-guide/jw_showcase/web/jw_showcase_for_web/

JW Showcase is provided as an open source tool to enable you to make these customizations; however, JW Player does not support/maintain custom builds for individual clients. Your developer should be familiar with building Angular applications in order to customize on top of JW Showcase. If he/she is blocked by a specific issue, we're happy to provide guidance on isolating the area of the app that will allow you to achieve your desired behavior. 

Thanks!
