### ISSUE TITLE
Embed Showcase within another website 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#85]
### Expected Behavior

I should be able to embed JW Player within another website so it becomes one website, with my existing information and the JW showcase under it. 

### Actual Behavior

JW Showcase is its own website. I can not add information to it. I would like to add text, bullets. Anything I want in HTML

### Steps to reproduce

1. Go to http://cntvnow.com/jwshowcase/ --> I want the JW showcase to appear on this website in the white space.
2. I want this gallery to appear in that white space: http://cntvnow.com/navc

I basically want the middle section of the Showcase...meaning the featured window slider (top playlist) and any additional playlist I create under it, I want to paste that on my own website.. Is this possible?

How can I add the Showcase in the blank space (white space) on this website?

http://cntvnow.com/jwshowcase/

Please hope so

PLEASE MARK URGENT

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by akashpatel0427** [comment]
I basically want the middle section of the Showcase...meaning the featured window slider (top playlist) and any additional playlist I create under it, I want to paste that on my own website.. Is this possible? 

Please hope so

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

I see you are using JW Showcase v2.0, is this intended? I suggest updating to the latest [release](https://github.com/jwplayer/jw-showcase/releases/tag/v3.0.0) which makes site embedding easier .

If you want to make changes to JW Showcase itself you should create a custom build yourself. See the [wiki page](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code) for more information.

To embed JW Showcase into your existing site you need to make the following edits in your existing HTML file:

1. add `ng-app="app" ng-controller="RootController as rootVm"` to your HTML tag.
2. add the following in the head section (note; you already using some meta tags):

```
  <base href="/jwplayer/">
  <meta name="description" content="Your description">
  <meta property="og:title" content="Your title">
  <meta property="og:description" content="Your description">
  <meta property="og:image" content="/images/social-image.jpg">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="styles/main.css">
```

3. Add ` class="jw-theme-{{ ::rootVm.config.theme }}"` to the body element
4. Add following HTML inside the body element and where JW Showcase should be rendered.

```
<ui-view></ui-view>
<div class="jw-cover jw-loading" ng-show="rootVm.appStore.loading">
  <div class="jw-loading-icon">
    <div class="jw-rotate-animation"><i class="jwy-icon-buffer"></i></div>
  </div>
</div>
<script src="scripts/vendor.js"></script>
<script>window.configLocation = './config.json';</script>
<script src="scripts/scripts.js"></script>
```

Upload all JW Showcase content to the `jwshowcase` directory or change the paths accordingly.

**Comment by akashpatel0427** [comment]
What do you mean create a custom build? If I make these changes will I be able to embed  it in that white space on the site I showed you?

**Comment by akashpatel0427** [comment]
And No I will update it to the newest one

**Comment by akashpatel0427** [comment]
``<!doctype html> <html class="no-js" ng-app="app" ng-controller="RootController as rootVm" ng-app="app" ng-controller="RootController as rootVm> <head> <<base href="/jwshowcase/">
  <meta name="description" content="Your description">
  <meta property="og:title" content="Your title">
  <meta property="og:description" content="Your description">
  <meta property="og:image" content="/images/social-image.jpg">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="styles/main.css">base href="http://cntvnow.com/gallery/"> <meta charset="utf-8"> <title>The Exhibitions Channel</title> <meta name="description" content="The Exhibitions Channel - Brought to you by CEIR, IAEE, EMB and CNTV."> <meta property="og:title" content="The Exhibitions Channel"> <meta property="og:description" content="The Exhibitions Channel - Brought to you by CEIR, IAEE, EMB and CNTV."> <meta property="og:image" content="http://www.theexhibitionschannel.com/images/social-image.jpg"> <meta name="viewport" content="width=device-width,initial-scale=1"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <link rel="stylesheet" href="styles/main.css"> <link rel="stylesheet" href="styles/custom.css"> <body class="jw-theme-{{ ::rootVm.config.theme }}" class="jw-theme-{{ ::rootVm.config.theme }}> <div class="jw-container"> <div ui-view=""></div> </div> <div class="jw-cover jw-loading" ng-show="rootVm.dataStore.loading" <ui-view></ui-view>
<div class="jw-cover jw-loading" ng-show="rootVm.appStore.loading">
  <div class="jw-loading-icon">
    <div class="jw-rotate-animation"><i class="jwy-icon-buffer"></i></div>
  </div>
</div>
<script src="scripts/vendor.js"></script>
<script>window.configLocation = './config.json';</script>
<script src="scripts/scripts.js"></script>> <div class="jw-loading-icon"> <div class="jw-loading-icon-animation"> <i class="jwy-icon-buffer"></i> </div> </div> </div> <div class="jw-cover jw-modal ng-cloak" ng-show="rootVm.dataStore.error"> <div class="jw-modal-container"> <div class="jw-modal-title">Our apologies, you have found an error!</div> <div class="jw-modal-message"> {{ rootVm.dataStore.error.message }} </div> </div> </div> <script src="scripts/vendor.js"></script> <script src="scripts/scripts.js"></script> <script>window.configLocation = './config.json';</script>``

**Comment by ChristiaanScheermeijer** [comment]
**What do you mean create a custom build?**

I meant that if you want to make changes in the JW Showcase application (i.e. adding extra information in the video page) you need to create a custom build. If you want to surround JW Showcase with existing HTML you don't need to create a custom build.

**you would not happen to have a sample file would you?**

No sorry, this is really specific to your existing site and will be different for each.

**This is my code.. It does not work..**

You've applied the changes to the wrong HTML file (see the duplicatie attributes). You should apply them to an existing HTML file which doesn't have showcase integrated. For example; you would take http://cntvnow.com/index.html and apply the steps from above.

**Comment by akashpatel0427** [comment]
So I would copy that exactly over? I am sorry its just hard for me to understand.. My apologies.

**Comment by akashpatel0427** [comment]
Please look at what is happening. Do you know why this is happening? It wont load?

Here is my index for http://cntvnow.com/jwshowcase: 

````<!doctype html> <html class= ng-app="app" ng-controller="RootController as rootVm"> <head> <base href="http://cntvnow.com/gallery">
  <meta name="description" content="Your description">
  <meta property="og:title" content="Your title">
  <meta property="og:description" content="Your description">
  <meta property="og:image" content="/images/social-image.jpg">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="http://cntvnow.com/gallery/styles/main.css"> <link rel="stylesheet" href="http://cntvnow.com/gallery/styles/custom.css"> <body class="jw-theme-{{ ::rootVm.config.theme }}"> 

 <div class="jw-container">
<ui-view></ui-view>
<div class="jw-cover jw-loading" ng-show="rootVm.appStore.loading">
  <div class="jw-loading-icon">
    <div class="jw-rotate-animation"><i class="jwy-icon-buffer"></i></div>
  </div>
</div>
<script src="http://cntvnow.com/gallery/scripts/vendor.js"></script>
<script>window.configLocation = 'http://cntvnow.com/gallery/config.json';</script>
<script src="http://cntvnow.com/gallery/scripts/scripts.js"></script> `

**Comment by akashpatel0427** [comment]
Sorry for the bother, this is an urgent matter. If there is anything I can do please let me know. I must get this up and running by early tomorrow morning..

**Comment by akashpatel0427** [comment]
Any help on this? Please:?

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

You are missing the `<base href="/jwshowcase/">` part in the `<head>` section

**Comment by akashpatel0427** [comment]
I need it to be a URL

**Comment by akashpatel0427** [comment]
I am embedding JW player onto a different website. Not its own. It needs to be a specific URL to call it

**Comment by akashpatel0427** [comment]
````````<html ng-app="app" ng-controller="RootController as rootVm">
<head> <base href="http://cntvnow.com/showcase/">
  <meta name="description" content="Your description">
  <meta property="og:title" content="Your title">
  <meta property="og:description" content="Your description">
  <meta property="og:image" content="/images/social-image.jpg">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="styles/main.css">
  
</head>
<body class="jw-theme-{{ ::rootVm.config.theme }}" <ui-view></ui-view>
<div class="jw-cover jw-loading" ng-show="rootVm.appStore.loading">
  <div class="jw-loading-icon">
    <div class="jw-rotate-animation"><i class="jwy-icon-buffer"></i></div>
  </div>
</div>>


<script src="scripts/vendor.js"></script>
<script>window.configLocation = './config.json';</script>
<script src="scripts/scripts.js"></script>

</body>
</html>```````

**Comment by akashpatel0427** [comment]
The first line is in the HTML tag as well it is not displaying properly in there. Here is a snapshot of my code
![screen shot 2017-01-17 at 9 30 29 am](https://cloud.githubusercontent.com/assets/20861873/22024328/9c94ab62-dc97-11e6-9398-a77e68c3d317.png)

**Comment by ChristiaanScheermeijer** [comment]
I've defined the subfolder where JW Showcase lives on your website. This is http://cntvnow.com/jwshowcase/ right?

**Comment by akashpatel0427** [comment]
The fonts, scripts, config.json file all live in this location ---> http://cntvnow.com/showcase/

**Comment by akashpatel0427** [comment]
I want to take this entire page and make it apart of http://cntvnow.com/jwshowcase

**Comment by ChristiaanScheermeijer** [comment]
It looks like you dropped the JW Showcase index.html file directly into a Wordpress page. You should make a separate template for the JW Showcase page and exclude all unnecessary includes (if this is possible, I'm not a Wordpress expert).

**Comment by akashpatel0427** [comment]
What if I just want to drop it in an html file with surrounding content? My main thing is I want to be able to drop it into an HTML file with existing content around it. Is that possible? I have been using w3schools html tester to see if that works and that does not either..

**Comment by ChristiaanScheermeijer** [comment]
That's not possible unfortunately, you need to 'merge' the JW Showcase index.html with your existing HTML file. You don't want this to show on all pages though, so I suggest creating a separate template for the Showcase page which is merged and contains the JW Showcase includes.

**Comment by akashpatel0427** [comment]
Well the last page I sent you is not hosted on wordpress. When I merge it all the content is deleted the showcase over powers my existing html

**Comment by ChristiaanScheermeijer** [comment]
If I understand you correctly you want to use JW Showcase as a widget? You could try using an iframe, but you will loose some functionality (e.g. sharing a link).

**Comment by akashpatel0427** [comment]
Yes so I want to take http://cntvnow.com/showcase and embed that directly inside an existing website such as http://cntvnow.com/rims or http://cntvnow.com/jwshowcase.... I want to take the JW showcase and embed it inside of an existing website with text... so putting it in the middle of a webpage with my existing site around it. Is that possible? 

Iframe is not the route I wanted to go but if thats the only option then thats all i can do.

**Comment by johnluther** [comment]
Hi, Akash. What you're trying to do is a bit beyond the intended use case for the pre-compiled app (i.e., a simple standalone gallery).

My recommendation would be to hire a freelance front-end web developer who knows AngularJS to help you out. A skilled developer could do this very quickly and affordably. He or she could also provide you with a template to make it easy to launch additional embedded sites so you don't have to manually recode every time.

I have never used Upwork but have heard good things from others: https://www.upwork.com/cat/developers/

**Comment by akashpatel0427** [comment]
Thank you, I will try and look into it..
