### ISSUE TITLE
Share function lingers (freezes) on screen

### ISSUE THREAD

**Issue by Charles-I-Blanton** [jwplayer/jw-showcase#86]
### Expected Behavior

When a user presses the share button, we're expecting the Facebook, Twitter and Email sharing options to appear -- when the button is tapped again, we're expecting the share icons and option to disappear from the user's view.

### Actual Behavior

When I press the share button, the icons appear just as expected. To remove the share options, often requires several pressings of the button, and if often freezes on screen, even after we've returned to the homepage and the rest of the page renders. 

### Steps to reproduce

1. Visit www.legendstv.com (www.legendstv.com/mobile/) from any mobile browser
2. Open any video from the homescreen
3. Press the share icon, to the bottom right of the player
4. Press the icon again to attempt to close the options, and refresh your screen to return to our homepage.

### Environment

iOS and Android mobile 
most recent showcase release
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @Charles-I-Blanton,

That is because the CSS of the 'backdrop' element is being overruled. Normally when you click on the backdrop element the share dialog will be closed. 

Removing the following override will fix the problem:

```
position: static !important;
```

**Comment by Charles-I-Blanton** [comment]
Pardeep, see below.
