### ISSUE TITLE
Cookies!

### ISSUE THREAD

**Issue by Charles-I-Blanton** [jwplayer/jw-showcase#88]
### Expected Behavior

Hi, two questions for you, here we go:

- What would be the operational impacts on our site if we remove cookies from being placed on end user devices? Can you please provide step by step instructions on how to do so. 

- Also, please provide step by step instructions on how to leave cookies in place, but remove the cookies notification screen from our showcase mobile site. 

We'd like to remove the cookies notification, on way or another.

### Actual Behavior

Cookies pop up.

### Steps to reproduce

1. visit www.legendstv.com (www.legendstv.com/mobile/) from any mobile device

### Environment

-ios 
-ANdroid

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
If you disable the cookies (technically local storage), you will lose continue watching (i.e., watch progress), Saved Videos and whether or not the user has enabled the conserve bandwidth option.

We haven't tested Showcase with cookies disabled and therefore don't recommend it.

To disable the cookies notification, clone the jw-showcase repo and build as explaiend in https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code, then edit the jw-showcase-lib/js/core/servicesuserSettings.service.js file. Change 'cookies: false' to 'cookies: true', then recompile the app (`grunt build`) and redeploy to your server.

Again, we do NOT recommend doing this as it could cause unexpected behavior in the app.

**Comment by Charles-I-Blanton** [comment]
Good morning,

Are these instructions for turning off cookies? Or for disabling the message. I'm 100% fine allowing cookies, but we do need to remove the notification from our app. 

Thanks and best,

Isaac 

Sent from my iPhone

**Comment by johnluther** [comment]
That is to disable the notification.

If you intend to offer your site in Europe, you should consider leaving the notification enabled in order to meet EU regulations (https://www.cookielaw.org/the-cookie-law/).

**Comment by Charles-I-Blanton** [comment]
OK, great, that's exactly what we need. Our licensing rights are for the US today, and we're certainly looking forward to expansion, thanks John.
