### ISSUE TITLE
Screen renders blank graphics after numerous refreshes

### ISSUE THREAD

**Issue by Charles-I-Blanton** [jwplayer/jw-showcase#89]
### Expected Behavior

We're expecting our homepage graphics to render each time the homepage is loaded.

### Actual Behavior

After several refreshes (admittedly, probably more refreshes than most users would attempt) the screen starts to reveal fewer and fewer of our homepage video thumbnail graphics. 

### Steps to reproduce

1. visit www.legendstv.com (www.legendstv.com/mobile/) from any mobile device
2. refresh the page continuously. It could take up to as many as 50+ refreshes to reproduce -- I've noticed the action on days where we're continuously developing and I'm spending a great deal of time on our mobile pages. Also, when I clear my cookies, the graphics reappear. 

### Environment

- *iPhone 5*
- *iOS | 10.2*
- *Up to date JW Showcase*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Have you seen this on multiple iOS devices, or just the one? I can't reproduce it on either iPhone 5 or 6. But you are correct, definitely an edge case.
