### ISSUE TITLE
Ads delivery is sometimey

### ISSUE THREAD

**Issue by ghost** [jwplayer/jw-showcase#90]
### Expected Behavior

In full screen mode, we're expecting our ads and podded ad groups to deliver seamlessly.

### Actual Behavior

About 1/3 of the time, we get the expected result. Other times, we'll hear the audio of the commercials, with the last frame of the video (pre-break) on screen, until the break is over and the film resumes. When this occurs, the player seems to restart at 00:00:01, then after a second or two, it jumps to the correct position. We'd love to see the commercials lay in consistently. 

### Steps to reproduce

1. visit www.legendstv.com/mobile and watch any film

### Environment

- iPhone 5
- iOS 10.2
- Current JW Showcase version

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment]
Does this happen during normal playback, or when you try to seek through the video?

**Comment by Charles-I-Blanton** [comment]
We're looking at normal playback scenarios

**Comment by Charles-I-Blanton** [comment]
*In full screen mode

**Comment by johnluther** [comment]
This ad tag ("Ferry Corsten Ad Pod") produces an error: http://www.legendstv.com/assets/98098_ferry-corsten-wkndr-a-year-in-the-life_ad1break1.xml. Seems to be some kind of test tag that calls the JW QA server?
