### ISSUE TITLE
Support links in video descriptions

### ISSUE THREAD

**Issue by johnluther** [jwplayer/jw-showcase#92]
### Expected Behavior

Customers can include a web link in the video's description. For example, to take users to a related news story on another site.

### Actual Behavior

If you try to include links in description metadata from JW Platform, they just show as text, not hyperlinks. This is also true if you try to use HTML markup in the description, b/c the markup gets escaped.

JW Platform JSON feeds can include a "link" element (set in the JW Dashboard) that we could use for customers to include links in descriptions. For example, at runtime in the video's watch page, if a 'link' is present in the feed, add a line to the description and populate it with the 'link' wrapped in an anchor tag.

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by akashpatel0427** [comment]
When will this be done?

**Comment by johnluther** [comment]
We are still looking into the feasibility of using the <link> element to do it and the UX. Marking it as 3.1 for now, but it's not a guarantee that we will add it.

**Comment by akashpatel0427** [comment]
Thank you, was wondering if this was possible to begin with. Thanks for the feedback.

**Comment by johnluther** [comment]
We have decided that the link element in the JW metadata wouldn't be a good solution for this (it is intended for a permalink to the video itself, not an external link). 

We are exploring what we think could be a better solution, supporting a minimal subset of Markdown tags (including hyperlinks) in the descriptions.
