### ISSUE TITLE
Showcase Website scroll:hidden

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#94]
### Expected Behavior

When you go to http://cntvnow.com/navc the page cuts off towards the bottom. The page should scroll to the very bottom of the page and display all content on the page. If I increase the size of the ad scrolling banner at the top it should display all the videos and pages correctly. It should not cut into the slider videos and the bottom most playlist. 

### Actual Behavior

When you scroll on http://cntvnow.com/navc the page cuts off. It does not let you scroll the full length of the actual page. If I increase the size of the banner up top the featured window slider videos get cut off. i.e. the bar sits midway through the main slider. 

### Steps to reproduce

1. Go to http://cntvnow.com/navc and scroll
2. Scroll to the bottom on a desktop notice that it will not scroll all the way down. 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

You're pushing the main view container down by adding the table on top. If you fix the height you can alter the height of the main view container with the following CSS (assuming the height is 34px):

```
.view-container {
    height: calc(100% - 34px);
}
```

**Comment by akashpatel0427** [comment]
It still cuts off some of the site, it is better is there a more responsive solution?

Thannk you much appreciated.

**Comment by akashpatel0427** [comment]
Any help with this? It still cuts off on desktop, the more you stretch it the more it gets cut off. Is there a responsive solution:?

**Comment by johnluther** [comment]
Setting it to height: calc(100% - 75px); fixed it for me (Chrome 56)

**Comment by akashpatel0427** [comment]
on a desktop yes when you shrink to mobile a white bar appears at the bottom, seems like it shrinks the container

**Comment by johnluther** [comment]
I think you should hire someone with Angular and CSS experience to help you out. Your site will perform better if it's done properly. There are a lot of inexpensive options on Fiverr (https://goo.gl/zEcy1Z)
