### ISSUE TITLE
Increase Banner Image Size 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#95]
### Expected Behavior

The banner at the top marked "Presented by SPARK" should be larger on all devices not just a desktop. Increase the size on the image (not scrolling banner).

### Actual Behavior

Used the previous custom.css Christian gave but it seems not to work with 3.0. Any advice on how to increase the size on the banner without it running off the white header area?

### Steps to reproduce

1. Go to http://cntvnow.com/navc
2.increase the size of SPARK logo without it running off the header area and without it affecting the scrolling of the website (meaning not cutting off website, able to scroll entire site top to bottom). 

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Here's the updated custom CSS:

```
.jw-header .jw-header-main .jw-header-logo {
    max-height: 90px;
}
```
