### ISSUE TITLE
Slider Window Cut Off

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#96]
### Expected Behavior

When I log onto http://cntvnow.com/showcase none of the videos should be cut off, I should be able to scroll from the top to the bottom of the page, with any size window (meaning scaling it larger or smaller, especially larger) and no thumbnail should be cut off. 

### Actual Behavior

When I go to http://cntvnow.com/showcase the slider window appears to be cut off because the size of the jw-header is large. The happens when I view the screen in full screen, the larger you make the screen the more it gets cut. 

### Steps to reproduce

1. http://cntvnow.com/showcase drag the window as large as you can 
2. Notice how the slider window gets cut

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

Currently JW Showcase is designed to have a fixed header and content height. The main header is 90px and the sub headers are 50px. When scaling to mobile screen size the main header height will become 60px.

You have removed the max-height property of the header logo so the header will grow outside these limits. The main content does not respond to these changes and will be covered by the header.

I think you have two options:

 1. Undo the max-height removal.
 2. Modify the SCSS/HTML source code and create a custom build. 

Hint: add the following snippet to `app/styles/main.scss` above the imports.
 
```
$header-height: 120px;
$header-height-mobile: 120px;
```
